.include "macro.inc"

/* assembler directives */
.set noat
.set noreorder
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.12.1 */

# Handwritten function
glabel func_80025C00
/* 1000 80025C00 3C088006 */  lui        $t0, %hi(D_8005A580)
/* 1004 80025C04 2508A580 */  addiu      $t0, $t0, %lo(D_8005A580)
/* 1008 80025C08 3C090018 */  lui        $t1, %hi(D_1814F0)
/* 100C 80025C0C 252914F0 */  addiu      $t1, $t1, %lo(D_1814F0)
.L80025C10:
/* 1010 80025C10 AD000000 */  sw         $zero, 0x0($t0)
/* 1014 80025C14 AD000004 */  sw         $zero, 0x4($t0)
/* 1018 80025C18 21080008 */  addi       $t0, $t0, 0x8 # handwritten instruction
/* 101C 80025C1C 2129FFF8 */  addi       $t1, $t1, -0x8 # handwritten instruction
/* 1020 80025C20 1520FFFB */  bnez       $t1, .L80025C10
/* 1024 80025C24 00000000 */   nop
/* 1028 80025C28 3C0A8003 */  lui        $t2, %hi(nuBoot)
/* 102C 80025C2C 254A9DF0 */  addiu      $t2, $t2, %lo(nuBoot)
/* 1030 80025C30 3C1D8016 */  lui        $sp, %hi(nuContNum)
/* 1034 80025C34 01400008 */  jr         $t2
/* 1038 80025C38 27BDD7F0 */   addiu     $sp, $sp, %lo(nuContNum)
/* 103C 80025C3C 00000000 */  nop
/* 1040 80025C40 00000000 */  nop
/* 1044 80025C44 00000000 */  nop
/* 1048 80025C48 00000000 */  nop
/* 104C 80025C4C 00000000 */  nop
