.include "macro.inc"

/* assembler directives */
.set noat
.set noreorder
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.12.1 */

# Handwritten function
glabel bcopy
/* BB70 80030770 10C0001B */  beqz       $a2, .L800307E0
/* BB74 80030774 00A03821 */   addu      $a3, $a1, $zero
/* BB78 80030778 10850019 */  beq        $a0, $a1, .L800307E0
/* BB7C 8003077C 00000000 */   nop
/* BB80 80030780 00A4082A */  slt        $at, $a1, $a0
/* BB84 80030784 14200007 */  bnez       $at, .L800307A4
/* BB88 80030788 00000000 */   nop
/* BB8C 8003078C 00861020 */  add        $v0, $a0, $a2 # handwritten instruction
/* BB90 80030790 00A2082A */  slt        $at, $a1, $v0
/* BB94 80030794 10200003 */  beqz       $at, .L800307A4
/* BB98 80030798 00000000 */   nop
/* BB9C 8003079C 1000005C */  b          .L80030910
/* BBA0 800307A0 00000000 */   nop
.L800307A4:
/* BBA4 800307A4 28C10010 */  slti       $at, $a2, 0x10
/* BBA8 800307A8 14200005 */  bnez       $at, .L800307C0
/* BBAC 800307AC 00000000 */   nop
/* BBB0 800307B0 30820003 */  andi       $v0, $a0, 0x3
/* BBB4 800307B4 30A30003 */  andi       $v1, $a1, 0x3
/* BBB8 800307B8 1043000B */  beq        $v0, $v1, .L800307E8
/* BBBC 800307BC 00000000 */   nop
.L800307C0:
/* BBC0 800307C0 10C00007 */  beqz       $a2, .L800307E0
/* BBC4 800307C4 00000000 */   nop
/* BBC8 800307C8 00861821 */  addu       $v1, $a0, $a2
.L800307CC:
/* BBCC 800307CC 80820000 */  lb         $v0, 0x0($a0)
/* BBD0 800307D0 24840001 */  addiu      $a0, $a0, 0x1
/* BBD4 800307D4 A0A20000 */  sb         $v0, 0x0($a1)
/* BBD8 800307D8 1483FFFC */  bne        $a0, $v1, .L800307CC
/* BBDC 800307DC 24A50001 */   addiu     $a1, $a1, 0x1
.L800307E0:
/* BBE0 800307E0 03E00008 */  jr         $ra
/* BBE4 800307E4 00E01021 */   addu      $v0, $a3, $zero
.L800307E8:
/* BBE8 800307E8 1040001A */  beqz       $v0, .L80030854
/* BBEC 800307EC 00000000 */   nop
/* BBF0 800307F0 24010001 */  addiu      $at, $zero, 0x1
/* BBF4 800307F4 10410010 */  beq        $v0, $at, .L80030838
/* BBF8 800307F8 00000000 */   nop
/* BBFC 800307FC 24010002 */  addiu      $at, $zero, 0x2
/* BC00 80030800 10410007 */  beq        $v0, $at, .L80030820
/* BC04 80030804 00000000 */   nop
/* BC08 80030808 80820000 */  lb         $v0, 0x0($a0)
/* BC0C 8003080C 24840001 */  addiu      $a0, $a0, 0x1
/* BC10 80030810 A0A20000 */  sb         $v0, 0x0($a1)
/* BC14 80030814 24A50001 */  addiu      $a1, $a1, 0x1
/* BC18 80030818 1000000E */  b          .L80030854
/* BC1C 8003081C 24C6FFFF */   addiu     $a2, $a2, -0x1
.L80030820:
/* BC20 80030820 84820000 */  lh         $v0, 0x0($a0)
/* BC24 80030824 24840002 */  addiu      $a0, $a0, 0x2
/* BC28 80030828 A4A20000 */  sh         $v0, 0x0($a1)
/* BC2C 8003082C 24A50002 */  addiu      $a1, $a1, 0x2
/* BC30 80030830 10000008 */  b          .L80030854
/* BC34 80030834 24C6FFFE */   addiu     $a2, $a2, -0x2
.L80030838:
/* BC38 80030838 80820000 */  lb         $v0, 0x0($a0)
/* BC3C 8003083C 84830001 */  lh         $v1, 0x1($a0)
/* BC40 80030840 24840003 */  addiu      $a0, $a0, 0x3
/* BC44 80030844 A0A20000 */  sb         $v0, 0x0($a1)
/* BC48 80030848 A4A30001 */  sh         $v1, 0x1($a1)
/* BC4C 8003084C 24A50003 */  addiu      $a1, $a1, 0x3
/* BC50 80030850 24C6FFFD */  addiu      $a2, $a2, -0x3
.L80030854:
/* BC54 80030854 28C10020 */  slti       $at, $a2, 0x20
/* BC58 80030858 14200015 */  bnez       $at, .L800308B0
/* BC5C 8003085C 00000000 */   nop
/* BC60 80030860 8C820000 */  lw         $v0, 0x0($a0)
/* BC64 80030864 8C830004 */  lw         $v1, 0x4($a0)
/* BC68 80030868 8C880008 */  lw         $t0, 0x8($a0)
/* BC6C 8003086C 8C89000C */  lw         $t1, 0xC($a0)
/* BC70 80030870 8C8A0010 */  lw         $t2, 0x10($a0)
/* BC74 80030874 8C8B0014 */  lw         $t3, 0x14($a0)
/* BC78 80030878 8C8C0018 */  lw         $t4, 0x18($a0)
/* BC7C 8003087C 8C8D001C */  lw         $t5, 0x1C($a0)
/* BC80 80030880 24840020 */  addiu      $a0, $a0, 0x20
/* BC84 80030884 ACA20000 */  sw         $v0, 0x0($a1)
/* BC88 80030888 ACA30004 */  sw         $v1, 0x4($a1)
/* BC8C 8003088C ACA80008 */  sw         $t0, 0x8($a1)
/* BC90 80030890 ACA9000C */  sw         $t1, 0xC($a1)
/* BC94 80030894 ACAA0010 */  sw         $t2, 0x10($a1)
/* BC98 80030898 ACAB0014 */  sw         $t3, 0x14($a1)
/* BC9C 8003089C ACAC0018 */  sw         $t4, 0x18($a1)
/* BCA0 800308A0 ACAD001C */  sw         $t5, 0x1C($a1)
/* BCA4 800308A4 24A50020 */  addiu      $a1, $a1, 0x20
/* BCA8 800308A8 1000FFEA */  b          .L80030854
/* BCAC 800308AC 24C6FFE0 */   addiu     $a2, $a2, -0x20
.L800308B0:
/* BCB0 800308B0 28C10010 */  slti       $at, $a2, 0x10
/* BCB4 800308B4 1420000D */  bnez       $at, .L800308EC
/* BCB8 800308B8 00000000 */   nop
/* BCBC 800308BC 8C820000 */  lw         $v0, 0x0($a0)
/* BCC0 800308C0 8C830004 */  lw         $v1, 0x4($a0)
/* BCC4 800308C4 8C880008 */  lw         $t0, 0x8($a0)
/* BCC8 800308C8 8C89000C */  lw         $t1, 0xC($a0)
/* BCCC 800308CC 24840010 */  addiu      $a0, $a0, 0x10
/* BCD0 800308D0 ACA20000 */  sw         $v0, 0x0($a1)
/* BCD4 800308D4 ACA30004 */  sw         $v1, 0x4($a1)
/* BCD8 800308D8 ACA80008 */  sw         $t0, 0x8($a1)
/* BCDC 800308DC ACA9000C */  sw         $t1, 0xC($a1)
/* BCE0 800308E0 24A50010 */  addiu      $a1, $a1, 0x10
/* BCE4 800308E4 1000FFF2 */  b          .L800308B0
/* BCE8 800308E8 24C6FFF0 */   addiu     $a2, $a2, -0x10
.L800308EC:
/* BCEC 800308EC 28C10004 */  slti       $at, $a2, 0x4
/* BCF0 800308F0 1420FFB3 */  bnez       $at, .L800307C0
/* BCF4 800308F4 00000000 */   nop
/* BCF8 800308F8 8C820000 */  lw         $v0, 0x0($a0)
/* BCFC 800308FC 24840004 */  addiu      $a0, $a0, 0x4
/* BD00 80030900 ACA20000 */  sw         $v0, 0x0($a1)
/* BD04 80030904 24A50004 */  addiu      $a1, $a1, 0x4
/* BD08 80030908 1000FFF8 */  b          .L800308EC
/* BD0C 8003090C 24C6FFFC */   addiu     $a2, $a2, -0x4
.L80030910:
/* BD10 80030910 00862020 */  add        $a0, $a0, $a2 # handwritten instruction
/* BD14 80030914 00A62820 */  add        $a1, $a1, $a2 # handwritten instruction
/* BD18 80030918 28C10010 */  slti       $at, $a2, 0x10
/* BD1C 8003091C 14200005 */  bnez       $at, .L80030934
/* BD20 80030920 00000000 */   nop
/* BD24 80030924 30820003 */  andi       $v0, $a0, 0x3
/* BD28 80030928 30A30003 */  andi       $v1, $a1, 0x3
/* BD2C 8003092C 1043000D */  beq        $v0, $v1, .L80030964
/* BD30 80030930 00000000 */   nop
.L80030934:
/* BD34 80030934 10C0FFAA */  beqz       $a2, .L800307E0
/* BD38 80030938 00000000 */   nop
/* BD3C 8003093C 2484FFFF */  addiu      $a0, $a0, -0x1
/* BD40 80030940 24A5FFFF */  addiu      $a1, $a1, -0x1
/* BD44 80030944 00861823 */  subu       $v1, $a0, $a2
.L80030948:
/* BD48 80030948 80820000 */  lb         $v0, 0x0($a0)
/* BD4C 8003094C 2484FFFF */  addiu      $a0, $a0, -0x1
/* BD50 80030950 A0A20000 */  sb         $v0, 0x0($a1)
/* BD54 80030954 1483FFFC */  bne        $a0, $v1, .L80030948
/* BD58 80030958 24A5FFFF */   addiu     $a1, $a1, -0x1
/* BD5C 8003095C 03E00008 */  jr         $ra
/* BD60 80030960 00E01021 */   addu      $v0, $a3, $zero
.L80030964:
/* BD64 80030964 1040001A */  beqz       $v0, .L800309D0
/* BD68 80030968 00000000 */   nop
/* BD6C 8003096C 24010003 */  addiu      $at, $zero, 0x3
/* BD70 80030970 10410010 */  beq        $v0, $at, .L800309B4
/* BD74 80030974 00000000 */   nop
/* BD78 80030978 24010002 */  addiu      $at, $zero, 0x2
/* BD7C 8003097C 10410007 */  beq        $v0, $at, .L8003099C
/* BD80 80030980 00000000 */   nop
/* BD84 80030984 8082FFFF */  lb         $v0, -0x1($a0)
/* BD88 80030988 2484FFFF */  addiu      $a0, $a0, -0x1
/* BD8C 8003098C A0A2FFFF */  sb         $v0, -0x1($a1)
/* BD90 80030990 24A5FFFF */  addiu      $a1, $a1, -0x1
/* BD94 80030994 1000000E */  b          .L800309D0
/* BD98 80030998 24C6FFFF */   addiu     $a2, $a2, -0x1
.L8003099C:
/* BD9C 8003099C 8482FFFE */  lh         $v0, -0x2($a0)
/* BDA0 800309A0 2484FFFE */  addiu      $a0, $a0, -0x2
/* BDA4 800309A4 A4A2FFFE */  sh         $v0, -0x2($a1)
/* BDA8 800309A8 24A5FFFE */  addiu      $a1, $a1, -0x2
/* BDAC 800309AC 10000008 */  b          .L800309D0
/* BDB0 800309B0 24C6FFFE */   addiu     $a2, $a2, -0x2
.L800309B4:
/* BDB4 800309B4 8082FFFF */  lb         $v0, -0x1($a0)
/* BDB8 800309B8 8483FFFD */  lh         $v1, -0x3($a0)
/* BDBC 800309BC 2484FFFD */  addiu      $a0, $a0, -0x3
/* BDC0 800309C0 A0A2FFFF */  sb         $v0, -0x1($a1)
/* BDC4 800309C4 A4A3FFFD */  sh         $v1, -0x3($a1)
/* BDC8 800309C8 24A5FFFD */  addiu      $a1, $a1, -0x3
/* BDCC 800309CC 24C6FFFD */  addiu      $a2, $a2, -0x3
.L800309D0:
/* BDD0 800309D0 28C10020 */  slti       $at, $a2, 0x20
/* BDD4 800309D4 14200015 */  bnez       $at, .L80030A2C
/* BDD8 800309D8 00000000 */   nop
/* BDDC 800309DC 8C82FFFC */  lw         $v0, -0x4($a0)
/* BDE0 800309E0 8C83FFF8 */  lw         $v1, -0x8($a0)
/* BDE4 800309E4 8C88FFF4 */  lw         $t0, -0xC($a0)
/* BDE8 800309E8 8C89FFF0 */  lw         $t1, -0x10($a0)
/* BDEC 800309EC 8C8AFFEC */  lw         $t2, -0x14($a0)
/* BDF0 800309F0 8C8BFFE8 */  lw         $t3, -0x18($a0)
/* BDF4 800309F4 8C8CFFE4 */  lw         $t4, -0x1C($a0)
/* BDF8 800309F8 8C8DFFE0 */  lw         $t5, -0x20($a0)
/* BDFC 800309FC 2484FFE0 */  addiu      $a0, $a0, -0x20
/* BE00 80030A00 ACA2FFFC */  sw         $v0, -0x4($a1)
/* BE04 80030A04 ACA3FFF8 */  sw         $v1, -0x8($a1)
/* BE08 80030A08 ACA8FFF4 */  sw         $t0, -0xC($a1)
/* BE0C 80030A0C ACA9FFF0 */  sw         $t1, -0x10($a1)
/* BE10 80030A10 ACAAFFEC */  sw         $t2, -0x14($a1)
/* BE14 80030A14 ACABFFE8 */  sw         $t3, -0x18($a1)
/* BE18 80030A18 ACACFFE4 */  sw         $t4, -0x1C($a1)
/* BE1C 80030A1C ACADFFE0 */  sw         $t5, -0x20($a1)
/* BE20 80030A20 24A5FFE0 */  addiu      $a1, $a1, -0x20
/* BE24 80030A24 1000FFEA */  b          .L800309D0
/* BE28 80030A28 24C6FFE0 */   addiu     $a2, $a2, -0x20
.L80030A2C:
/* BE2C 80030A2C 28C10010 */  slti       $at, $a2, 0x10
/* BE30 80030A30 1420000D */  bnez       $at, .L80030A68
/* BE34 80030A34 00000000 */   nop
/* BE38 80030A38 8C82FFFC */  lw         $v0, -0x4($a0)
/* BE3C 80030A3C 8C83FFF8 */  lw         $v1, -0x8($a0)
/* BE40 80030A40 8C88FFF4 */  lw         $t0, -0xC($a0)
/* BE44 80030A44 8C89FFF0 */  lw         $t1, -0x10($a0)
/* BE48 80030A48 2484FFF0 */  addiu      $a0, $a0, -0x10
/* BE4C 80030A4C ACA2FFFC */  sw         $v0, -0x4($a1)
/* BE50 80030A50 ACA3FFF8 */  sw         $v1, -0x8($a1)
/* BE54 80030A54 ACA8FFF4 */  sw         $t0, -0xC($a1)
/* BE58 80030A58 ACA9FFF0 */  sw         $t1, -0x10($a1)
/* BE5C 80030A5C 24A5FFF0 */  addiu      $a1, $a1, -0x10
/* BE60 80030A60 1000FFF2 */  b          .L80030A2C
/* BE64 80030A64 24C6FFF0 */   addiu     $a2, $a2, -0x10
.L80030A68:
/* BE68 80030A68 28C10004 */  slti       $at, $a2, 0x4
/* BE6C 80030A6C 1420FFB1 */  bnez       $at, .L80030934
/* BE70 80030A70 00000000 */   nop
/* BE74 80030A74 8C82FFFC */  lw         $v0, -0x4($a0)
/* BE78 80030A78 2484FFFC */  addiu      $a0, $a0, -0x4
/* BE7C 80030A7C ACA2FFFC */  sw         $v0, -0x4($a1)
/* BE80 80030A80 24A5FFFC */  addiu      $a1, $a1, -0x4
/* BE84 80030A84 1000FFF8 */  b          .L80030A68
/* BE88 80030A88 24C6FFFC */   addiu     $a2, $a2, -0x4
/* BE8C 80030A8C 00000000 */  nop
