.include "macro.inc"

/* assembler directives */
.set noat
.set noreorder
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.12.1 */

glabel func_80030A90
/* BE90 80030A90 00041823 */  negu       $v1, $a0
/* BE94 80030A94 28A1000C */  slti       $at, $a1, 0xC
/* BE98 80030A98 1420001D */  bnez       $at, .L80030B10
/* BE9C 80030A9C 00000000 */   nop
/* BEA0 80030AA0 30630003 */  andi       $v1, $v1, 0x3
/* BEA4 80030AA4 10600003 */  beqz       $v1, .L80030AB4
/* BEA8 80030AA8 00A32823 */   subu      $a1, $a1, $v1
/* BEAC 80030AAC A8800000 */  swl        $zero, 0x0($a0)
/* BEB0 80030AB0 00832021 */  addu       $a0, $a0, $v1
.L80030AB4:
/* BEB4 80030AB4 2401FFE0 */  addiu      $at, $zero, -0x20
/* BEB8 80030AB8 00A13824 */  and        $a3, $a1, $at
/* BEBC 80030ABC 10E0000C */  beqz       $a3, .L80030AF0
/* BEC0 80030AC0 00A72823 */   subu      $a1, $a1, $a3
/* BEC4 80030AC4 00E43821 */  addu       $a3, $a3, $a0
.L80030AC8:
/* BEC8 80030AC8 AC800000 */  sw         $zero, 0x0($a0)
/* BECC 80030ACC AC800004 */  sw         $zero, 0x4($a0)
/* BED0 80030AD0 AC800008 */  sw         $zero, 0x8($a0)
/* BED4 80030AD4 AC80000C */  sw         $zero, 0xC($a0)
/* BED8 80030AD8 24840020 */  addiu      $a0, $a0, 0x20
/* BEDC 80030ADC AC80FFF0 */  sw         $zero, -0x10($a0)
/* BEE0 80030AE0 AC80FFF4 */  sw         $zero, -0xC($a0)
/* BEE4 80030AE4 AC80FFF8 */  sw         $zero, -0x8($a0)
/* BEE8 80030AE8 1487FFF7 */  bne        $a0, $a3, .L80030AC8
/* BEEC 80030AEC AC80FFFC */   sw        $zero, -0x4($a0)
.L80030AF0:
/* BEF0 80030AF0 2401FFFC */  addiu      $at, $zero, -0x4
/* BEF4 80030AF4 00A13824 */  and        $a3, $a1, $at
/* BEF8 80030AF8 10E00005 */  beqz       $a3, .L80030B10
/* BEFC 80030AFC 00A72823 */   subu      $a1, $a1, $a3
/* BF00 80030B00 00E43821 */  addu       $a3, $a3, $a0
.L80030B04:
/* BF04 80030B04 24840004 */  addiu      $a0, $a0, 0x4
/* BF08 80030B08 1487FFFE */  bne        $a0, $a3, .L80030B04
/* BF0C 80030B0C AC80FFFC */   sw        $zero, -0x4($a0)
.L80030B10:
/* BF10 80030B10 18A00005 */  blez       $a1, .L80030B28
/* BF14 80030B14 00000000 */   nop
/* BF18 80030B18 00A42821 */  addu       $a1, $a1, $a0
.L80030B1C:
/* BF1C 80030B1C 24840001 */  addiu      $a0, $a0, 0x1
/* BF20 80030B20 1485FFFE */  bne        $a0, $a1, .L80030B1C
/* BF24 80030B24 A080FFFF */   sb        $zero, -0x1($a0)
.L80030B28:
/* BF28 80030B28 03E00008 */  jr         $ra
/* BF2C 80030B2C 00000000 */   nop
