.include "macro.inc"

/* assembler directives */
.set noat
.set noreorder
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.12.1 */

# Handwritten function
glabel func_800393D0
/* 147D0 800393D0 3C1A8004 */  lui        $k0, %hi(.L800394A4) # handwritten instruction
/* 147D4 800393D4 275A94A4 */  addiu      $k0, $k0, %lo(.L800394A4) # handwritten instruction
/* 147D8 800393D8 03400008 */  jr         $k0
/* 147DC 800393DC 00000000 */   nop
D_800393E0:
/* 147E0 800393E0 AFBAFFF0 */  sw         $k0, -0x10($sp) # handwritten instruction
/* 147E4 800393E4 10000003 */  b          .L800393F4
/* 147E8 800393E8 3C1A8004 */   lui       $k0, %hi(D_80039400) # handwritten instruction
/* 147EC 800393EC 00000000 */  nop
/* 147F0 800393F0 00000000 */  nop
.L800393F4:
/* 147F4 800393F4 275A9400 */  addiu      $k0, $k0, %lo(D_80039400) # handwritten instruction
/* 147F8 800393F8 03400008 */  jr         $k0
/* 147FC 800393FC 00000000 */   nop
D_80039400:
/* 14800 80039400 401A6800 */  mfc0       $k0, $13 # handwritten instruction
/* 14804 80039404 335A007C */  andi       $k0, $k0, 0x7C # handwritten instruction
/* 14808 80039408 17400008 */  bnez       $k0, .L8003942C # handwritten instruction
/* 1480C 8003940C 001AD082 */   srl       $k0, $k0, 2
/* 14810 80039410 401A6800 */  mfc0       $k0, $13 # handwritten instruction
/* 14814 80039414 00000000 */  nop
/* 14818 80039418 335A4000 */  andi       $k0, $k0, 0x4000 # handwritten instruction
/* 1481C 8003941C 13400021 */  beqz       $k0, .L800394A4 # handwritten instruction
/* 14820 80039420 00000000 */   nop
/* 14824 80039424 0800E512 */  j          .L80039448
/* 14828 80039428 00000000 */   nop
.L8003942C:
/* 1482C 8003942C AFBBFFF8 */  sw         $k1, -0x8($sp) # handwritten instruction
/* 14830 80039430 3C1B8006 */  lui        $k1, %hi(D_80059FF4) # handwritten instruction
/* 14834 80039434 277B9FF4 */  addiu      $k1, $k1, %lo(D_80059FF4) # handwritten instruction
/* 14838 80039438 037AD820 */  add        $k1, $k1, $k0 # handwritten instruction
/* 1483C 8003943C 937A0000 */  lbu        $k0, 0x0($k1) # handwritten instruction
/* 14840 80039440 13400018 */  beqz       $k0, .L800394A4 # handwritten instruction
/* 14844 80039444 00000000 */   nop
.L80039448:
/* 14848 80039448 3C1AA460 */  lui        $k0, %hi(D_A4600010) # handwritten instruction
/* 1484C 8003944C 8F5A0010 */  lw         $k0, %lo(D_A4600010)($k0) # handwritten instruction
/* 14850 80039450 00000000 */  nop
/* 14854 80039454 335A0003 */  andi       $k0, $k0, 0x3 # handwritten instruction
/* 14858 80039458 1740FFFB */  bnez       $k0, .L80039448 # handwritten instruction
/* 1485C 8003945C 00000000 */   nop
/* 14860 80039460 3C1ABFF1 */  lui        $k0, %hi(D_BFF08004) # handwritten instruction
/* 14864 80039464 8F5A8004 */  lw         $k0, %lo(D_BFF08004)($k0) # handwritten instruction
/* 14868 80039468 00000000 */  nop
/* 1486C 8003946C 335A0008 */  andi       $k0, $k0, 0x8 # handwritten instruction
/* 14870 80039470 17400005 */  bnez       $k0, .L80039488 # handwritten instruction
/* 14874 80039474 3C1ABFF0 */   lui       $k0, (0xBFF00014 >> 16) # handwritten instruction
/* 14878 80039478 375A0014 */  ori        $k0, $k0, (0xBFF00014 & 0xFFFF) # handwritten instruction
/* 1487C 8003947C 8FBBFFF8 */  lw         $k1, -0x8($sp) # handwritten instruction
/* 14880 80039480 03400008 */  jr         $k0
/* 14884 80039484 27BDFFA0 */   addiu     $sp, $sp, -0x60
.L80039488:
/* 14888 80039488 401A7000 */  mfc0       $k0, $14 # handwritten instruction
/* 1488C 8003948C 3C1BBFF1 */  lui        $k1, %hi(D_BFF08000) # handwritten instruction
/* 14890 80039490 AF7A8000 */  sw         $k0, %lo(D_BFF08000)($k1) # handwritten instruction
/* 14894 80039494 8FBBFFF8 */  lw         $k1, -0x8($sp) # handwritten instruction
/* 14898 80039498 8FBAFFF0 */  lw         $k0, -0x10($sp) # handwritten instruction
/* 1489C 8003949C 42000018 */  eret # handwritten instruction
/* 148A0 800394A0 00000000 */  nop
.L800394A4:
/* 148A4 800394A4 3C1A8013 */  lui        $k0, %hi(D_8012AFD0) # handwritten instruction
/* 148A8 800394A8 275AAFD0 */  addiu      $k0, $k0, %lo(D_8012AFD0) # handwritten instruction
/* 148AC 800394AC FF410020 */  sd         $at, 0x20($k0) # handwritten instruction
/* 148B0 800394B0 401B6000 */  mfc0       $k1, $12 # handwritten instruction
/* 148B4 800394B4 AF5B0118 */  sw         $k1, 0x118($k0) # handwritten instruction
/* 148B8 800394B8 2401FFFC */  addiu      $at, $zero, -0x4
/* 148BC 800394BC 0361D824 */  and        $k1, $k1, $at
/* 148C0 800394C0 409B6000 */  mtc0       $k1, $12 # handwritten instruction
/* 148C4 800394C4 FF480058 */  sd         $t0, 0x58($k0) # handwritten instruction
/* 148C8 800394C8 FF490060 */  sd         $t1, 0x60($k0) # handwritten instruction
/* 148CC 800394CC FF4A0068 */  sd         $t2, 0x68($k0) # handwritten instruction
/* 148D0 800394D0 AF400018 */  sw         $zero, 0x18($k0) # handwritten instruction
/* 148D4 800394D4 40086800 */  mfc0       $t0, $13 # handwritten instruction
/* 148D8 800394D8 3C0A8013 */  lui        $t2, %hi(D_8012AFCC)
/* 148DC 800394DC 8D4AAFCC */  lw         $t2, %lo(D_8012AFCC)($t2)
/* 148E0 800394E0 154000DD */  bnez       $t2, .L80039858
/* 148E4 800394E4 00000000 */   nop
/* 148E8 800394E8 3109007C */  andi       $t1, $t0, 0x7C
/* 148EC 800394EC 240A0000 */  addiu      $t2, $zero, 0x0
/* 148F0 800394F0 152A00D9 */  bne        $t1, $t2, .L80039858
/* 148F4 800394F4 00000000 */   nop
/* 148F8 800394F8 03684824 */  and        $t1, $k1, $t0
/* 148FC 800394FC 312A4000 */  andi       $t2, $t1, 0x4000
/* 14900 80039500 114000A3 */  beqz       $t2, .L80039790
/* 14904 80039504 00000000 */   nop
/* 14908 80039508 3C09C000 */  lui        $t1, (0xC0000008 >> 16)
/* 1490C 8003950C 35290008 */  ori        $t1, $t1, (0xC0000008 & 0xFFFF)
/* 14910 80039510 AD200000 */  sw         $zero, 0x0($t1)
.L80039514:
/* 14914 80039514 40086800 */  mfc0       $t0, $13 # handwritten instruction
/* 14918 80039518 31084000 */  andi       $t0, $t0, 0x4000
/* 1491C 8003951C 1408FFFD */  bne        $zero, $t0, .L80039514
/* 14920 80039520 00000000 */   nop
/* 14924 80039524 3C0AC000 */  lui        $t2, (0xC0000000 >> 16)
/* 14928 80039528 8D480000 */  lw         $t0, (0xC0000000 & 0xFFFF)($t2)
/* 1492C 8003952C 00084E82 */  srl        $t1, $t0, 26
/* 14930 80039530 3129003F */  andi       $t1, $t1, 0x3F
/* 14934 80039534 240A0010 */  addiu      $t2, $zero, 0x10
/* 14938 80039538 112A0041 */  beq        $t1, $t2, .L80039640
/* 1493C 8003953C 00000000 */   nop
/* 14940 80039540 240A000E */  addiu      $t2, $zero, 0xE
/* 14944 80039544 112A0066 */  beq        $t1, $t2, .L800396E0
/* 14948 80039548 00000000 */   nop
/* 1494C 8003954C 240A0014 */  addiu      $t2, $zero, 0x14
/* 14950 80039550 112A0022 */  beq        $t1, $t2, .L800395DC
/* 14954 80039554 00000000 */   nop
/* 14958 80039558 240A000F */  addiu      $t2, $zero, 0xF
/* 1495C 8003955C 112A0022 */  beq        $t1, $t2, .L800395E8
/* 14960 80039560 00000000 */   nop
/* 14964 80039564 240A0011 */  addiu      $t2, $zero, 0x11
/* 14968 80039568 112A0025 */  beq        $t1, $t2, .L80039600
/* 1496C 8003956C 00000000 */   nop
/* 14970 80039570 240A000D */  addiu      $t2, $zero, 0xD
/* 14974 80039574 112A0026 */  beq        $t1, $t2, .L80039610
/* 14978 80039578 00000000 */   nop
/* 1497C 8003957C 240A0012 */  addiu      $t2, $zero, 0x12
/* 14980 80039580 112A0027 */  beq        $t1, $t2, .L80039620
/* 14984 80039584 00000000 */   nop
/* 14988 80039588 240A0013 */  addiu      $t2, $zero, 0x13
/* 1498C 8003958C 112A0028 */  beq        $t1, $t2, .L80039630
/* 14990 80039590 00000000 */   nop
/* 14994 80039594 240A0015 */  addiu      $t2, $zero, 0x15
/* 14998 80039598 112A0003 */  beq        $t1, $t2, .L800395A8
/* 1499C 8003959C 00000000 */   nop
/* 149A0 800395A0 100000A2 */  b          .L8003982C
/* 149A4 800395A4 00000000 */   nop
.L800395A8:
/* 149A8 800395A8 240A0001 */  addiu      $t2, $zero, 0x1
/* 149AC 800395AC 00084C02 */  srl        $t1, $t0, 16
/* 149B0 800395B0 312900FF */  andi       $t1, $t1, 0xFF
/* 149B4 800395B4 112A0005 */  beq        $t1, $t2, .L800395CC
/* 149B8 800395B8 00000000 */   nop
/* 149BC 800395BC 240A00A8 */  addiu      $t2, $zero, 0xA8
/* 149C0 800395C0 3C018005 */  lui        $at, %hi(D_80054084)
/* 149C4 800395C4 100000A4 */  b          .L80039858
/* 149C8 800395C8 AC2A4084 */   sw        $t2, %lo(D_80054084)($at)
.L800395CC:
/* 149CC 800395CC 240A00B0 */  addiu      $t2, $zero, 0xB0
/* 149D0 800395D0 3C018005 */  lui        $at, %hi(D_80054084)
/* 149D4 800395D4 100000A0 */  b          .L80039858
/* 149D8 800395D8 AC2A4084 */   sw        $t2, %lo(D_80054084)($at)
.L800395DC:
/* 149DC 800395DC 3C018005 */  lui        $at, %hi(D_80054088)
/* 149E0 800395E0 1000009D */  b          .L80039858
/* 149E4 800395E4 AC284088 */   sw        $t0, %lo(D_80054088)($at)
.L800395E8:
/* 149E8 800395E8 3C0A00FF */  lui        $t2, (0xFFFFFF >> 16)
/* 149EC 800395EC 354AFFFF */  ori        $t2, $t2, (0xFFFFFF & 0xFFFF)
/* 149F0 800395F0 010A4824 */  and        $t1, $t0, $t2
/* 149F4 800395F4 3C018005 */  lui        $at, %hi(D_80054080)
/* 149F8 800395F8 1000008C */  b          .L8003982C
/* 149FC 800395FC AC294080 */   sw        $t1, %lo(D_80054080)($at)
.L80039600:
/* 14A00 80039600 240A0088 */  addiu      $t2, $zero, 0x88
/* 14A04 80039604 3C018005 */  lui        $at, %hi(D_80054084)
/* 14A08 80039608 10000093 */  b          .L80039858
/* 14A0C 8003960C AC2A4084 */   sw        $t2, %lo(D_80054084)($at)
.L80039610:
/* 14A10 80039610 240A0080 */  addiu      $t2, $zero, 0x80
/* 14A14 80039614 3C018005 */  lui        $at, %hi(D_80054084)
/* 14A18 80039618 1000008F */  b          .L80039858
/* 14A1C 8003961C AC2A4084 */   sw        $t2, %lo(D_80054084)($at)
.L80039620:
/* 14A20 80039620 240A0090 */  addiu      $t2, $zero, 0x90
/* 14A24 80039624 3C018005 */  lui        $at, %hi(D_80054084)
/* 14A28 80039628 1000008B */  b          .L80039858
/* 14A2C 8003962C AC2A4084 */   sw        $t2, %lo(D_80054084)($at)
.L80039630:
/* 14A30 80039630 240A0098 */  addiu      $t2, $zero, 0x98
/* 14A34 80039634 3C018005 */  lui        $at, %hi(D_80054084)
/* 14A38 80039638 10000087 */  b          .L80039858
/* 14A3C 8003963C AC2A4084 */   sw        $t2, %lo(D_80054084)($at)
.L80039640:
/* 14A40 80039640 00084E02 */  srl        $t1, $t0, 24
/* 14A44 80039644 31290003 */  andi       $t1, $t1, 0x3
/* 14A48 80039648 10090078 */  beq        $zero, $t1, .L8003982C
/* 14A4C 8003964C 00000000 */   nop
/* 14A50 80039650 3C0A8013 */  lui        $t2, %hi(D_80133378)
/* 14A54 80039654 8D4A3378 */  lw         $t2, %lo(D_80133378)($t2)
/* 14A58 80039658 01495023 */  subu       $t2, $t2, $t1
/* 14A5C 8003965C 3C018013 */  lui        $at, %hi(D_80133378)
/* 14A60 80039660 AC2A3378 */  sw         $t2, %lo(D_80133378)($at)
/* 14A64 80039664 FF4B0070 */  sd         $t3, 0x70($k0) # handwritten instruction
/* 14A68 80039668 3C0B801B */  lui        $t3, %hi(D_801AAA80)
/* 14A6C 8003966C 8D6BAA80 */  lw         $t3, %lo(D_801AAA80)($t3)
/* 14A70 80039670 00085402 */  srl        $t2, $t0, 16
/* 14A74 80039674 314A00FF */  andi       $t2, $t2, 0xFF
/* 14A78 80039678 A16A0000 */  sb         $t2, 0x0($t3)
/* 14A7C 8003967C 216B0001 */  addi       $t3, $t3, 0x1 # handwritten instruction
/* 14A80 80039680 2129FFFF */  addi       $t1, $t1, -0x1 # handwritten instruction
/* 14A84 80039684 1009000B */  beq        $zero, $t1, .L800396B4
/* 14A88 80039688 00000000 */   nop
/* 14A8C 8003968C 00085202 */  srl        $t2, $t0, 8
/* 14A90 80039690 314A00FF */  andi       $t2, $t2, 0xFF
/* 14A94 80039694 A16A0000 */  sb         $t2, 0x0($t3)
/* 14A98 80039698 216B0001 */  addi       $t3, $t3, 0x1 # handwritten instruction
/* 14A9C 8003969C 2129FFFF */  addi       $t1, $t1, -0x1 # handwritten instruction
/* 14AA0 800396A0 10090004 */  beq        $zero, $t1, .L800396B4
/* 14AA4 800396A4 00000000 */   nop
/* 14AA8 800396A8 310800FF */  andi       $t0, $t0, 0xFF
/* 14AAC 800396AC A1680000 */  sb         $t0, 0x0($t3)
/* 14AB0 800396B0 216B0001 */  addi       $t3, $t3, 0x1 # handwritten instruction
.L800396B4:
/* 14AB4 800396B4 3C01801B */  lui        $at, %hi(D_801AAA80)
/* 14AB8 800396B8 AC2BAA80 */  sw         $t3, %lo(D_801AAA80)($at)
/* 14ABC 800396BC DF4B0070 */  ld         $t3, 0x70($k0) # handwritten instruction
/* 14AC0 800396C0 3C0A8013 */  lui        $t2, %hi(D_80133378)
/* 14AC4 800396C4 8D4A3378 */  lw         $t2, %lo(D_80133378)($t2)
/* 14AC8 800396C8 140A0058 */  bne        $zero, $t2, .L8003982C
/* 14ACC 800396CC 00000000 */   nop
/* 14AD0 800396D0 240A0078 */  addiu      $t2, $zero, 0x78
/* 14AD4 800396D4 3C018005 */  lui        $at, %hi(D_80054084)
/* 14AD8 800396D8 1000005F */  b          .L80039858
/* 14ADC 800396DC AC2A4084 */   sw        $t2, %lo(D_80054084)($at)
.L800396E0:
/* 14AE0 800396E0 00084E02 */  srl        $t1, $t0, 24
/* 14AE4 800396E4 31290003 */  andi       $t1, $t1, 0x3
/* 14AE8 800396E8 10090050 */  beq        $zero, $t1, .L8003982C
/* 14AEC 800396EC 00000000 */   nop
/* 14AF0 800396F0 3C0A8005 */  lui        $t2, %hi(D_80054080)
/* 14AF4 800396F4 8D4A4080 */  lw         $t2, %lo(D_80054080)($t2)
/* 14AF8 800396F8 01495023 */  subu       $t2, $t2, $t1
/* 14AFC 800396FC 3C018005 */  lui        $at, %hi(D_80054080)
/* 14B00 80039700 AC2A4080 */  sw         $t2, %lo(D_80054080)($at)
/* 14B04 80039704 FF4B0070 */  sd         $t3, 0x70($k0) # handwritten instruction
/* 14B08 80039708 3C0B800F */  lui        $t3, %hi(D_800F2618)
/* 14B0C 8003970C 8D6B2618 */  lw         $t3, %lo(D_800F2618)($t3)
/* 14B10 80039710 140B0003 */  bne        $zero, $t3, .L80039720
/* 14B14 80039714 00000000 */   nop
/* 14B18 80039718 10000044 */  b          .L8003982C
/* 14B1C 8003971C DF4B0070 */   ld        $t3, 0x70($k0) # handwritten instruction
.L80039720:
/* 14B20 80039720 00085402 */  srl        $t2, $t0, 16
/* 14B24 80039724 314A00FF */  andi       $t2, $t2, 0xFF
/* 14B28 80039728 A16A0000 */  sb         $t2, 0x0($t3)
/* 14B2C 8003972C 216B0001 */  addi       $t3, $t3, 0x1 # handwritten instruction
/* 14B30 80039730 2129FFFF */  addi       $t1, $t1, -0x1 # handwritten instruction
/* 14B34 80039734 1009000B */  beq        $zero, $t1, .L80039764
/* 14B38 80039738 00000000 */   nop
/* 14B3C 8003973C 00085202 */  srl        $t2, $t0, 8
/* 14B40 80039740 314A00FF */  andi       $t2, $t2, 0xFF
/* 14B44 80039744 A16A0000 */  sb         $t2, 0x0($t3)
/* 14B48 80039748 216B0001 */  addi       $t3, $t3, 0x1 # handwritten instruction
/* 14B4C 8003974C 2129FFFF */  addi       $t1, $t1, -0x1 # handwritten instruction
/* 14B50 80039750 10090004 */  beq        $zero, $t1, .L80039764
/* 14B54 80039754 00000000 */   nop
/* 14B58 80039758 310800FF */  andi       $t0, $t0, 0xFF
/* 14B5C 8003975C A1680000 */  sb         $t0, 0x0($t3)
/* 14B60 80039760 216B0001 */  addi       $t3, $t3, 0x1 # handwritten instruction
.L80039764:
/* 14B64 80039764 3C01800F */  lui        $at, %hi(D_800F2618)
/* 14B68 80039768 AC2B2618 */  sw         $t3, %lo(D_800F2618)($at)
/* 14B6C 8003976C DF4B0070 */  ld         $t3, 0x70($k0) # handwritten instruction
/* 14B70 80039770 3C0A8005 */  lui        $t2, %hi(D_80054080)
/* 14B74 80039774 8D4A4080 */  lw         $t2, %lo(D_80054080)($t2)
/* 14B78 80039778 140A002C */  bne        $zero, $t2, .L8003982C
/* 14B7C 8003977C 00000000 */   nop
/* 14B80 80039780 240A00A0 */  addiu      $t2, $zero, 0xA0
/* 14B84 80039784 3C018005 */  lui        $at, %hi(D_80054084)
/* 14B88 80039788 10000033 */  b          .L80039858
/* 14B8C 8003978C AC2A4084 */   sw        $t2, %lo(D_80054084)($at)
.L80039790:
/* 14B90 80039790 312A2000 */  andi       $t2, $t1, 0x2000
/* 14B94 80039794 11400030 */  beqz       $t2, .L80039858
/* 14B98 80039798 00000000 */   nop
/* 14B9C 8003979C 3C09C000 */  lui        $t1, (0xC000000C >> 16)
/* 14BA0 800397A0 3529000C */  ori        $t1, $t1, (0xC000000C & 0xFFFF)
/* 14BA4 800397A4 AD200000 */  sw         $zero, 0x0($t1)
/* 14BA8 800397A8 3C0A801B */  lui        $t2, %hi(D_801ABA30)
/* 14BAC 800397AC 8D4ABA30 */  lw         $t2, %lo(D_801ABA30)($t2)
/* 14BB0 800397B0 15400005 */  bnez       $t2, .L800397C8
/* 14BB4 800397B4 00000000 */   nop
/* 14BB8 800397B8 240A0001 */  addiu      $t2, $zero, 0x1
/* 14BBC 800397BC 3C018005 */  lui        $at, %hi(D_80052BA0)
/* 14BC0 800397C0 1000001A */  b          .L8003982C
/* 14BC4 800397C4 AC2A2BA0 */   sw        $t2, %lo(D_80052BA0)($at)
.L800397C8:
/* 14BC8 800397C8 214AFFFF */  addi       $t2, $t2, -0x1 # handwritten instruction
/* 14BCC 800397CC 3C01801B */  lui        $at, %hi(D_801ABA30)
/* 14BD0 800397D0 AC2ABA30 */  sw         $t2, %lo(D_801ABA30)($at)
/* 14BD4 800397D4 3C08801B */  lui        $t0, %hi(D_801AAD58)
/* 14BD8 800397D8 8D08AD58 */  lw         $t0, %lo(D_801AAD58)($t0)
/* 14BDC 800397DC 3C098018 */  lui        $t1, %hi(D_8017FD68)
/* 14BE0 800397E0 8D29FD68 */  lw         $t1, %lo(D_8017FD68)($t1)
/* 14BE4 800397E4 00095080 */  sll        $t2, $t1, 2
/* 14BE8 800397E8 01484020 */  add        $t0, $t2, $t0 # handwritten instruction
/* 14BEC 800397EC 8D0A0000 */  lw         $t2, 0x0($t0)
/* 14BF0 800397F0 21290001 */  addi       $t1, $t1, 0x1 # handwritten instruction
/* 14BF4 800397F4 3C088013 */  lui        $t0, %hi(D_801333C0)
/* 14BF8 800397F8 8D0833C0 */  lw         $t0, %lo(D_801333C0)($t0)
/* 14BFC 800397FC 01094022 */  sub        $t0, $t0, $t1 # handwritten instruction
/* 14C00 80039800 1D000002 */  bgtz       $t0, .L8003980C
/* 14C04 80039804 00000000 */   nop
/* 14C08 80039808 24090000 */  addiu      $t1, $zero, 0x0
.L8003980C:
/* 14C0C 8003980C 3C018018 */  lui        $at, %hi(D_8017FD68)
/* 14C10 80039810 AC29FD68 */  sw         $t1, %lo(D_8017FD68)($at)
.L80039814:
/* 14C14 80039814 40086800 */  mfc0       $t0, $13 # handwritten instruction
/* 14C18 80039818 31082000 */  andi       $t0, $t0, 0x2000
/* 14C1C 8003981C 1408FFFD */  bne        $zero, $t0, .L80039814
/* 14C20 80039820 00000000 */   nop
/* 14C24 80039824 3C08C000 */  lui        $t0, (0xC0000000 >> 16)
/* 14C28 80039828 AD0A0000 */  sw         $t2, (0xC0000000 & 0xFFFF)($t0)
.L8003982C:
/* 14C2C 8003982C DF480058 */  ld         $t0, 0x58($k0) # handwritten instruction
/* 14C30 80039830 DF490060 */  ld         $t1, 0x60($k0) # handwritten instruction
/* 14C34 80039834 DF4A0068 */  ld         $t2, 0x68($k0) # handwritten instruction
/* 14C38 80039838 DF410020 */  ld         $at, 0x20($k0) # handwritten instruction
/* 14C3C 8003983C 8F5B0118 */  lw         $k1, 0x118($k0) # handwritten instruction
/* 14C40 80039840 409B6000 */  mtc0       $k1, $12 # handwritten instruction
/* 14C44 80039844 00000000 */  nop
/* 14C48 80039848 00000000 */  nop
/* 14C4C 8003984C 00000000 */  nop
/* 14C50 80039850 00000000 */  nop
/* 14C54 80039854 42000018 */  eret # handwritten instruction
.L80039858:
/* 14C58 80039858 03404021 */  addu       $t0, $k0, $zero
/* 14C5C 8003985C 3C1A8005 */  lui        $k0, %hi(D_80052BF0) # handwritten instruction
/* 14C60 80039860 8F5A2BF0 */  lw         $k0, %lo(D_80052BF0)($k0) # handwritten instruction
/* 14C64 80039864 DD090020 */  ld         $t1, 0x20($t0)
/* 14C68 80039868 FF490020 */  sd         $t1, 0x20($k0) # handwritten instruction
/* 14C6C 8003986C DD090118 */  ld         $t1, 0x118($t0)
/* 14C70 80039870 FF490118 */  sd         $t1, 0x118($k0) # handwritten instruction
/* 14C74 80039874 DD090058 */  ld         $t1, 0x58($t0)
/* 14C78 80039878 FF490058 */  sd         $t1, 0x58($k0) # handwritten instruction
/* 14C7C 8003987C DD090060 */  ld         $t1, 0x60($t0)
/* 14C80 80039880 FF490060 */  sd         $t1, 0x60($k0) # handwritten instruction
/* 14C84 80039884 DD090068 */  ld         $t1, 0x68($t0)
/* 14C88 80039888 FF490068 */  sd         $t1, 0x68($k0) # handwritten instruction
/* 14C8C 8003988C FF420028 */  sd         $v0, 0x28($k0) # handwritten instruction
/* 14C90 80039890 FF430030 */  sd         $v1, 0x30($k0) # handwritten instruction
/* 14C94 80039894 FF440038 */  sd         $a0, 0x38($k0) # handwritten instruction
/* 14C98 80039898 FF450040 */  sd         $a1, 0x40($k0) # handwritten instruction
/* 14C9C 8003989C FF460048 */  sd         $a2, 0x48($k0) # handwritten instruction
/* 14CA0 800398A0 FF470050 */  sd         $a3, 0x50($k0) # handwritten instruction
/* 14CA4 800398A4 FF4B0070 */  sd         $t3, 0x70($k0) # handwritten instruction
/* 14CA8 800398A8 FF4C0078 */  sd         $t4, 0x78($k0) # handwritten instruction
/* 14CAC 800398AC FF4D0080 */  sd         $t5, 0x80($k0) # handwritten instruction
/* 14CB0 800398B0 FF4E0088 */  sd         $t6, 0x88($k0) # handwritten instruction
/* 14CB4 800398B4 FF4F0090 */  sd         $t7, 0x90($k0) # handwritten instruction
/* 14CB8 800398B8 FF500098 */  sd         $s0, 0x98($k0) # handwritten instruction
/* 14CBC 800398BC FF5100A0 */  sd         $s1, 0xA0($k0) # handwritten instruction
/* 14CC0 800398C0 FF5200A8 */  sd         $s2, 0xA8($k0) # handwritten instruction
/* 14CC4 800398C4 FF5300B0 */  sd         $s3, 0xB0($k0) # handwritten instruction
/* 14CC8 800398C8 FF5400B8 */  sd         $s4, 0xB8($k0) # handwritten instruction
/* 14CCC 800398CC FF5500C0 */  sd         $s5, 0xC0($k0) # handwritten instruction
/* 14CD0 800398D0 FF5600C8 */  sd         $s6, 0xC8($k0) # handwritten instruction
/* 14CD4 800398D4 FF5700D0 */  sd         $s7, 0xD0($k0) # handwritten instruction
/* 14CD8 800398D8 FF5800D8 */  sd         $t8, 0xD8($k0) # handwritten instruction
/* 14CDC 800398DC FF5900E0 */  sd         $t9, 0xE0($k0) # handwritten instruction
/* 14CE0 800398E0 FF5C00E8 */  sd         $gp, 0xE8($k0) # handwritten instruction
/* 14CE4 800398E4 FF5D00F0 */  sd         $sp, 0xF0($k0) # handwritten instruction
/* 14CE8 800398E8 FF5E00F8 */  sd         $fp, 0xF8($k0) # handwritten instruction
/* 14CEC 800398EC FF5F0100 */  sd         $ra, 0x100($k0) # handwritten instruction
/* 14CF0 800398F0 00004012 */  mflo       $t0
/* 14CF4 800398F4 FF480108 */  sd         $t0, 0x108($k0) # handwritten instruction
/* 14CF8 800398F8 00004010 */  mfhi       $t0
/* 14CFC 800398FC FF480110 */  sd         $t0, 0x110($k0) # handwritten instruction
/* 14D00 80039900 8F5B0118 */  lw         $k1, 0x118($k0) # handwritten instruction
/* 14D04 80039904 3369FF00 */  andi       $t1, $k1, 0xFF00 # handwritten instruction
/* 14D08 80039908 11200013 */  beqz       $t1, .L80039958
/* 14D0C 8003990C 00000000 */   nop
/* 14D10 80039910 3C088005 */  lui        $t0, %hi(D_80053DE0)
/* 14D14 80039914 25083DE0 */  addiu      $t0, $t0, %lo(D_80053DE0)
/* 14D18 80039918 8D080000 */  lw         $t0, 0x0($t0)
/* 14D1C 8003991C 2401FFFF */  addiu      $at, $zero, -0x1
/* 14D20 80039920 01015026 */  xor        $t2, $t0, $at
/* 14D24 80039924 314AFF00 */  andi       $t2, $t2, 0xFF00
/* 14D28 80039928 012A6025 */  or         $t4, $t1, $t2
/* 14D2C 8003992C 3C01FFFF */  lui        $at, (0xFFFF00FF >> 16)
/* 14D30 80039930 342100FF */  ori        $at, $at, (0xFFFF00FF & 0xFFFF)
/* 14D34 80039934 03615824 */  and        $t3, $k1, $at
/* 14D38 80039938 016C5825 */  or         $t3, $t3, $t4
/* 14D3C 8003993C AF4B0118 */  sw         $t3, 0x118($k0) # handwritten instruction
/* 14D40 80039940 3108FF00 */  andi       $t0, $t0, 0xFF00
/* 14D44 80039944 01284824 */  and        $t1, $t1, $t0
/* 14D48 80039948 3C01FFFF */  lui        $at, (0xFFFF00FF >> 16)
/* 14D4C 8003994C 342100FF */  ori        $at, $at, (0xFFFF00FF & 0xFFFF)
/* 14D50 80039950 0361D824 */  and        $k1, $k1, $at
/* 14D54 80039954 0369D825 */  or         $k1, $k1, $t1
.L80039958:
/* 14D58 80039958 3C09A430 */  lui        $t1, %hi(D_A430000C)
/* 14D5C 8003995C 8D29000C */  lw         $t1, %lo(D_A430000C)($t1)
/* 14D60 80039960 1120000B */  beqz       $t1, .L80039990
/* 14D64 80039964 00000000 */   nop
/* 14D68 80039968 3C088005 */  lui        $t0, %hi(D_80053DE0)
/* 14D6C 8003996C 25083DE0 */  addiu      $t0, $t0, %lo(D_80053DE0)
/* 14D70 80039970 8D080000 */  lw         $t0, 0x0($t0)
/* 14D74 80039974 00084402 */  srl        $t0, $t0, 16
/* 14D78 80039978 2401FFFF */  addiu      $at, $zero, -0x1
/* 14D7C 8003997C 01014026 */  xor        $t0, $t0, $at
/* 14D80 80039980 3108003F */  andi       $t0, $t0, 0x3F
/* 14D84 80039984 8F4C0128 */  lw         $t4, 0x128($k0) # handwritten instruction
/* 14D88 80039988 010C4024 */  and        $t0, $t0, $t4
/* 14D8C 8003998C 01284825 */  or         $t1, $t1, $t0
.L80039990:
/* 14D90 80039990 AF490128 */  sw         $t1, 0x128($k0) # handwritten instruction
/* 14D94 80039994 40087000 */  mfc0       $t0, $14 # handwritten instruction
/* 14D98 80039998 AF48011C */  sw         $t0, 0x11C($k0) # handwritten instruction
/* 14D9C 8003999C 8F480018 */  lw         $t0, 0x18($k0) # handwritten instruction
/* 14DA0 800399A0 11000014 */  beqz       $t0, .L800399F4
/* 14DA4 800399A4 00000000 */   nop
/* 14DA8 800399A8 4448F800 */  cfc1       $t0, $31
/* 14DAC 800399AC 00000000 */  nop
/* 14DB0 800399B0 AF48012C */  sw         $t0, 0x12C($k0) # handwritten instruction
/* 14DB4 800399B4 F7400130 */  sdc1       $f0, 0x130($k0)
/* 14DB8 800399B8 F7420138 */  sdc1       $f2, 0x138($k0)
/* 14DBC 800399BC F7440140 */  sdc1       $f4, 0x140($k0)
/* 14DC0 800399C0 F7460148 */  sdc1       $f6, 0x148($k0)
/* 14DC4 800399C4 F7480150 */  sdc1       $f8, 0x150($k0)
/* 14DC8 800399C8 F74A0158 */  sdc1       $f10, 0x158($k0)
/* 14DCC 800399CC F74C0160 */  sdc1       $f12, 0x160($k0)
/* 14DD0 800399D0 F74E0168 */  sdc1       $f14, 0x168($k0)
/* 14DD4 800399D4 F7500170 */  sdc1       $f16, 0x170($k0)
/* 14DD8 800399D8 F7520178 */  sdc1       $f18, 0x178($k0)
/* 14DDC 800399DC F7540180 */  sdc1       $f20, 0x180($k0)
/* 14DE0 800399E0 F7560188 */  sdc1       $f22, 0x188($k0)
/* 14DE4 800399E4 F7580190 */  sdc1       $f24, 0x190($k0)
/* 14DE8 800399E8 F75A0198 */  sdc1       $f26, 0x198($k0)
/* 14DEC 800399EC F75C01A0 */  sdc1       $f28, 0x1A0($k0)
/* 14DF0 800399F0 F75E01A8 */  sdc1       $f30, 0x1A8($k0)
.L800399F4:
/* 14DF4 800399F4 40086800 */  mfc0       $t0, $13 # handwritten instruction
/* 14DF8 800399F8 AF480120 */  sw         $t0, 0x120($k0) # handwritten instruction
/* 14DFC 800399FC 24090002 */  addiu      $t1, $zero, 0x2
/* 14E00 80039A00 A7490010 */  sh         $t1, 0x10($k0) # handwritten instruction
/* 14E04 80039A04 3C048005 */  lui        $a0, %hi(D_80054088)
/* 14E08 80039A08 8C844088 */  lw         $a0, %lo(D_80054088)($a0)
/* 14E0C 80039A0C 10800006 */  beqz       $a0, .L80039A28
/* 14E10 80039A10 00000000 */   nop
/* 14E14 80039A14 3C018005 */  lui        $at, %hi(D_80054088)
/* 14E18 80039A18 0C00EBA5 */  jal        func_8003AE94
/* 14E1C 80039A1C AC204088 */   sw        $zero, %lo(D_80054088)($at)
/* 14E20 80039A20 1000018C */  b          .L8003A054
/* 14E24 80039A24 00000000 */   nop
.L80039A28:
/* 14E28 80039A28 3C048005 */  lui        $a0, %hi(D_80054084)
/* 14E2C 80039A2C 8C844084 */  lw         $a0, %lo(D_80054084)($a0)
/* 14E30 80039A30 10800005 */  beqz       $a0, .L80039A48
/* 14E34 80039A34 00000000 */   nop
/* 14E38 80039A38 3C018005 */  lui        $at, %hi(D_80054084)
/* 14E3C 80039A3C 0C00E779 */  jal        func_80039DE4
/* 14E40 80039A40 AC204084 */   sw        $zero, %lo(D_80054084)($at)
/* 14E44 80039A44 8F480120 */  lw         $t0, 0x120($k0) # handwritten instruction
.L80039A48:
/* 14E48 80039A48 3109007C */  andi       $t1, $t0, 0x7C
/* 14E4C 80039A4C 240A0024 */  addiu      $t2, $zero, 0x24
/* 14E50 80039A50 112A00BF */  beq        $t1, $t2, .L80039D50
/* 14E54 80039A54 00000000 */   nop
/* 14E58 80039A58 240A002C */  addiu      $t2, $zero, 0x2C
/* 14E5C 80039A5C 112A0110 */  beq        $t1, $t2, .L80039EA0
/* 14E60 80039A60 00000000 */   nop
/* 14E64 80039A64 240A0000 */  addiu      $t2, $zero, 0x0
/* 14E68 80039A68 152A00D2 */  bne        $t1, $t2, .L80039DB4
/* 14E6C 80039A6C 00000000 */   nop
/* 14E70 80039A70 03688024 */  and        $s0, $k1, $t0
.L80039A74:
/* 14E74 80039A74 3209FF00 */  andi       $t1, $s0, 0xFF00
/* 14E78 80039A78 00095302 */  srl        $t2, $t1, 12
/* 14E7C 80039A7C 15400003 */  bnez       $t2, .L80039A8C
/* 14E80 80039A80 00000000 */   nop
/* 14E84 80039A84 00095202 */  srl        $t2, $t1, 8
/* 14E88 80039A88 214A0010 */  addi       $t2, $t2, 0x10 # handwritten instruction
.L80039A8C:
/* 14E8C 80039A8C 3C018006 */  lui        $at, %hi(D_80059FB0)
/* 14E90 80039A90 002A0821 */  addu       $at, $at, $t2
/* 14E94 80039A94 902A9FB0 */  lbu        $t2, %lo(D_80059FB0)($at)
/* 14E98 80039A98 3C018006 */  lui        $at, %hi(jtbl_80059FD0)
/* 14E9C 80039A9C 002A0821 */  addu       $at, $at, $t2
/* 14EA0 80039AA0 8C2A9FD0 */  lw         $t2, %lo(jtbl_80059FD0)($at)
/* 14EA4 80039AA4 01400008 */  jr         $t2
/* 14EA8 80039AA8 00000000 */   nop
glabel .L80039AAC
/* 14EAC 80039AAC 2401DFFF */  addiu      $at, $zero, -0x2001
/* 14EB0 80039AB0 1000FFF0 */  b          .L80039A74
/* 14EB4 80039AB4 02018024 */   and       $s0, $s0, $at
glabel .L80039AB8
/* 14EB8 80039AB8 2401BFFF */  addiu      $at, $zero, -0x4001
/* 14EBC 80039ABC 1000FFED */  b          .L80039A74
/* 14EC0 80039AC0 02018024 */   and       $s0, $s0, $at
glabel .L80039AC4
/* 14EC4 80039AC4 40095800 */  mfc0       $t1, $11 # handwritten instruction
/* 14EC8 80039AC8 40895800 */  mtc0       $t1, $11 # handwritten instruction
/* 14ECC 80039ACC 24040018 */  addiu      $a0, $zero, 0x18
/* 14ED0 80039AD0 0C00E779 */  jal        func_80039DE4
/* 14ED4 80039AD4 00000000 */   nop
/* 14ED8 80039AD8 3C01FFFF */  lui        $at, (0xFFFF7FFF >> 16)
/* 14EDC 80039ADC 34217FFF */  ori        $at, $at, (0xFFFF7FFF & 0xFFFF)
/* 14EE0 80039AE0 1000FFE4 */  b          .L80039A74
/* 14EE4 80039AE4 02018024 */   and       $s0, $s0, $at
glabel .L80039AE8
/* 14EE8 80039AE8 2401F7FF */  addiu      $at, $zero, -0x801
/* 14EEC 80039AEC 02018024 */  and        $s0, $s0, $at
/* 14EF0 80039AF0 3C098005 */  lui        $t1, %hi(D_80054050)
/* 14EF4 80039AF4 25294050 */  addiu      $t1, $t1, %lo(D_80054050)
/* 14EF8 80039AF8 21290008 */  addi       $t1, $t1, 0x8 # handwritten instruction
/* 14EFC 80039AFC 8D2A0000 */  lw         $t2, 0x0($t1)
/* 14F00 80039B00 11400007 */  beqz       $t2, .L80039B20
/* 14F04 80039B04 00000000 */   nop
/* 14F08 80039B08 0140F809 */  jalr       $t2
/* 14F0C 80039B0C 8D3D0004 */   lw        $sp, 0x4($t1)
/* 14F10 80039B10 10400003 */  beqz       $v0, .L80039B20
/* 14F14 80039B14 00000000 */   nop
/* 14F18 80039B18 10000093 */  b          .L80039D68
/* 14F1C 80039B1C 00000000 */   nop
.L80039B20:
/* 14F20 80039B20 0C00E779 */  jal        func_80039DE4
/* 14F24 80039B24 24040010 */   addiu     $a0, $zero, 0x10
/* 14F28 80039B28 1000FFD2 */  b          .L80039A74
/* 14F2C 80039B2C 00000000 */   nop
glabel .L80039B30
/* 14F30 80039B30 3C11A430 */  lui        $s1, %hi(D_A4300008)
/* 14F34 80039B34 8E310008 */  lw         $s1, %lo(D_A4300008)($s1)
/* 14F38 80039B38 3C088005 */  lui        $t0, %hi(D_80053DE0)
/* 14F3C 80039B3C 25083DE0 */  addiu      $t0, $t0, %lo(D_80053DE0)
/* 14F40 80039B40 8D080000 */  lw         $t0, 0x0($t0)
/* 14F44 80039B44 00084402 */  srl        $t0, $t0, 16
/* 14F48 80039B48 02288824 */  and        $s1, $s1, $t0
/* 14F4C 80039B4C 32290001 */  andi       $t1, $s1, 0x1
/* 14F50 80039B50 11200014 */  beqz       $t1, .L80039BA4
/* 14F54 80039B54 00000000 */   nop
/* 14F58 80039B58 3231003E */  andi       $s1, $s1, 0x3E
/* 14F5C 80039B5C 3C0CA404 */  lui        $t4, %hi(D_A4040010)
/* 14F60 80039B60 8D8C0010 */  lw         $t4, %lo(D_A4040010)($t4)
/* 14F64 80039B64 34098008 */  ori        $t1, $zero, 0x8008
/* 14F68 80039B68 3C01A404 */  lui        $at, %hi(D_A4040010)
/* 14F6C 80039B6C AC290010 */  sw         $t1, %lo(D_A4040010)($at)
/* 14F70 80039B70 318C0300 */  andi       $t4, $t4, 0x300
/* 14F74 80039B74 11800007 */  beqz       $t4, .L80039B94
/* 14F78 80039B78 00000000 */   nop
/* 14F7C 80039B7C 0C00E779 */  jal        func_80039DE4
/* 14F80 80039B80 24040020 */   addiu     $a0, $zero, 0x20
/* 14F84 80039B84 12200044 */  beqz       $s1, .L80039C98
/* 14F88 80039B88 00000000 */   nop
/* 14F8C 80039B8C 10000005 */  b          .L80039BA4
/* 14F90 80039B90 00000000 */   nop
.L80039B94:
/* 14F94 80039B94 0C00E779 */  jal        func_80039DE4
/* 14F98 80039B98 24040058 */   addiu     $a0, $zero, 0x58
/* 14F9C 80039B9C 1220003E */  beqz       $s1, .L80039C98
/* 14FA0 80039BA0 00000000 */   nop
.L80039BA4:
/* 14FA4 80039BA4 32290008 */  andi       $t1, $s1, 0x8
/* 14FA8 80039BA8 11200008 */  beqz       $t1, .L80039BCC
/* 14FAC 80039BAC 00000000 */   nop
/* 14FB0 80039BB0 32310037 */  andi       $s1, $s1, 0x37
/* 14FB4 80039BB4 3C01A440 */  lui        $at, %hi(D_A4400010)
/* 14FB8 80039BB8 AC200010 */  sw         $zero, %lo(D_A4400010)($at)
/* 14FBC 80039BBC 0C00E779 */  jal        func_80039DE4
/* 14FC0 80039BC0 24040038 */   addiu     $a0, $zero, 0x38
/* 14FC4 80039BC4 12200034 */  beqz       $s1, .L80039C98
/* 14FC8 80039BC8 00000000 */   nop
.L80039BCC:
/* 14FCC 80039BCC 32290004 */  andi       $t1, $s1, 0x4
/* 14FD0 80039BD0 11200009 */  beqz       $t1, .L80039BF8
/* 14FD4 80039BD4 00000000 */   nop
/* 14FD8 80039BD8 3231003B */  andi       $s1, $s1, 0x3B
/* 14FDC 80039BDC 24090001 */  addiu      $t1, $zero, 0x1
/* 14FE0 80039BE0 3C01A450 */  lui        $at, %hi(D_A450000C)
/* 14FE4 80039BE4 AC29000C */  sw         $t1, %lo(D_A450000C)($at)
/* 14FE8 80039BE8 0C00E779 */  jal        func_80039DE4
/* 14FEC 80039BEC 24040030 */   addiu     $a0, $zero, 0x30
/* 14FF0 80039BF0 12200029 */  beqz       $s1, .L80039C98
/* 14FF4 80039BF4 00000000 */   nop
.L80039BF8:
/* 14FF8 80039BF8 32290002 */  andi       $t1, $s1, 0x2
/* 14FFC 80039BFC 11200008 */  beqz       $t1, .L80039C20
/* 15000 80039C00 00000000 */   nop
/* 15004 80039C04 3231003D */  andi       $s1, $s1, 0x3D
/* 15008 80039C08 3C01A480 */  lui        $at, %hi(D_A4800018)
/* 1500C 80039C0C AC200018 */  sw         $zero, %lo(D_A4800018)($at)
/* 15010 80039C10 0C00E779 */  jal        func_80039DE4
/* 15014 80039C14 24040028 */   addiu     $a0, $zero, 0x28
/* 15018 80039C18 1220001F */  beqz       $s1, .L80039C98
/* 1501C 80039C1C 00000000 */   nop
.L80039C20:
/* 15020 80039C20 32290010 */  andi       $t1, $s1, 0x10
/* 15024 80039C24 11200013 */  beqz       $t1, .L80039C74
/* 15028 80039C28 00000000 */   nop
/* 1502C 80039C2C 3231002F */  andi       $s1, $s1, 0x2F
/* 15030 80039C30 24090002 */  addiu      $t1, $zero, 0x2
/* 15034 80039C34 3C01A460 */  lui        $at, %hi(D_A4600010)
/* 15038 80039C38 AC290010 */  sw         $t1, %lo(D_A4600010)($at)
/* 1503C 80039C3C 3C098005 */  lui        $t1, %hi(D_80054078)
/* 15040 80039C40 25294078 */  addiu      $t1, $t1, %lo(D_80054078)
/* 15044 80039C44 8D2A0000 */  lw         $t2, 0x0($t1)
/* 15048 80039C48 11400006 */  beqz       $t2, .L80039C64
/* 1504C 80039C4C 00000000 */   nop
/* 15050 80039C50 8D3D0004 */  lw         $sp, 0x4($t1)
/* 15054 80039C54 0140F809 */  jalr       $t2
/* 15058 80039C58 00402021 */   addu      $a0, $v0, $zero
/* 1505C 80039C5C 14400003 */  bnez       $v0, .L80039C6C
/* 15060 80039C60 00000000 */   nop
.L80039C64:
/* 15064 80039C64 0C00E779 */  jal        func_80039DE4
/* 15068 80039C68 24040040 */   addiu     $a0, $zero, 0x40
.L80039C6C:
/* 1506C 80039C6C 1220000A */  beqz       $s1, .L80039C98
/* 15070 80039C70 00000000 */   nop
.L80039C74:
/* 15074 80039C74 32290020 */  andi       $t1, $s1, 0x20
/* 15078 80039C78 11200007 */  beqz       $t1, .L80039C98
/* 1507C 80039C7C 00000000 */   nop
/* 15080 80039C80 3231001F */  andi       $s1, $s1, 0x1F
/* 15084 80039C84 24090800 */  addiu      $t1, $zero, 0x800
/* 15088 80039C88 3C01A430 */  lui        $at, %hi(D_A4300000)
/* 1508C 80039C8C AC290000 */  sw         $t1, %lo(D_A4300000)($at)
/* 15090 80039C90 0C00E779 */  jal        func_80039DE4
/* 15094 80039C94 24040048 */   addiu     $a0, $zero, 0x48
.L80039C98:
/* 15098 80039C98 2401FBFF */  addiu      $at, $zero, -0x401
/* 1509C 80039C9C 1000FF75 */  b          .L80039A74
/* 150A0 80039CA0 02018024 */   and       $s0, $s0, $at
glabel .L80039CA4
/* 150A4 80039CA4 8F5B0118 */  lw         $k1, 0x118($k0) # handwritten instruction
/* 150A8 80039CA8 2401EFFF */  addiu      $at, $zero, -0x1001
/* 150AC 80039CAC 0361D824 */  and        $k1, $k1, $at
/* 150B0 80039CB0 AF5B0118 */  sw         $k1, 0x118($k0) # handwritten instruction
/* 150B4 80039CB4 3C098005 */  lui        $t1, %hi(D_80053DDC)
/* 150B8 80039CB8 25293DDC */  addiu      $t1, $t1, %lo(D_80053DDC)
/* 150BC 80039CBC 8D2A0000 */  lw         $t2, 0x0($t1)
/* 150C0 80039CC0 11400004 */  beqz       $t2, .L80039CD4
/* 150C4 80039CC4 00000000 */   nop
/* 150C8 80039CC8 2401EFFF */  addiu      $at, $zero, -0x1001
/* 150CC 80039CCC 10000026 */  b          .L80039D68
/* 150D0 80039CD0 02018024 */   and       $s0, $s0, $at
.L80039CD4:
/* 150D4 80039CD4 240A0001 */  addiu      $t2, $zero, 0x1
/* 150D8 80039CD8 AD2A0000 */  sw         $t2, 0x0($t1)
/* 150DC 80039CDC 0C00E779 */  jal        func_80039DE4
/* 150E0 80039CE0 24040070 */   addiu     $a0, $zero, 0x70
/* 150E4 80039CE4 2401EFFF */  addiu      $at, $zero, -0x1001
/* 150E8 80039CE8 02018024 */  and        $s0, $s0, $at
/* 150EC 80039CEC 3C0A8005 */  lui        $t2, %hi(D_80052BE8)
/* 150F0 80039CF0 8D4A2BE8 */  lw         $t2, %lo(D_80052BE8)($t2)
/* 150F4 80039CF4 8D5B0118 */  lw         $k1, 0x118($t2) # handwritten instruction
/* 150F8 80039CF8 2401EFFF */  addiu      $at, $zero, -0x1001
/* 150FC 80039CFC 0361D824 */  and        $k1, $k1, $at
/* 15100 80039D00 10000019 */  b          .L80039D68
/* 15104 80039D04 AD5B0118 */   sw        $k1, 0x118($t2) # handwritten instruction
glabel .L80039D08
/* 15108 80039D08 2401FDFF */  addiu      $at, $zero, -0x201
/* 1510C 80039D0C 01014024 */  and        $t0, $t0, $at
/* 15110 80039D10 40886800 */  mtc0       $t0, $13 # handwritten instruction
/* 15114 80039D14 24040008 */  addiu      $a0, $zero, 0x8
/* 15118 80039D18 0C00E779 */  jal        func_80039DE4
/* 1511C 80039D1C 00000000 */   nop
/* 15120 80039D20 2401FDFF */  addiu      $at, $zero, -0x201
/* 15124 80039D24 1000FF53 */  b          .L80039A74
/* 15128 80039D28 02018024 */   and       $s0, $s0, $at
glabel .L80039D2C
/* 1512C 80039D2C 2401FEFF */  addiu      $at, $zero, -0x101
/* 15130 80039D30 01014024 */  and        $t0, $t0, $at
/* 15134 80039D34 40886800 */  mtc0       $t0, $13 # handwritten instruction
/* 15138 80039D38 24040000 */  addiu      $a0, $zero, 0x0
/* 1513C 80039D3C 0C00E779 */  jal        func_80039DE4
/* 15140 80039D40 00000000 */   nop
/* 15144 80039D44 2401FEFF */  addiu      $at, $zero, -0x101
/* 15148 80039D48 1000FF4A */  b          .L80039A74
/* 1514C 80039D4C 02018024 */   and       $s0, $s0, $at
.L80039D50:
/* 15150 80039D50 24090001 */  addiu      $t1, $zero, 0x1
/* 15154 80039D54 A7490012 */  sh         $t1, 0x12($k0) # handwritten instruction
/* 15158 80039D58 0C00E779 */  jal        func_80039DE4
/* 1515C 80039D5C 24040050 */   addiu     $a0, $zero, 0x50
/* 15160 80039D60 10000001 */  b          .L80039D68
/* 15164 80039D64 00000000 */   nop
glabel .L80039D68
/* 15168 80039D68 8F490004 */  lw         $t1, 0x4($k0) # handwritten instruction
/* 1516C 80039D6C 3C0A8005 */  lui        $t2, %hi(D_80052BE8)
/* 15170 80039D70 8D4A2BE8 */  lw         $t2, %lo(D_80052BE8)($t2)
/* 15174 80039D74 8D4B0004 */  lw         $t3, 0x4($t2)
/* 15178 80039D78 012B082A */  slt        $at, $t1, $t3
/* 1517C 80039D7C 10200007 */  beqz       $at, .L80039D9C
/* 15180 80039D80 00000000 */   nop
/* 15184 80039D84 03402821 */  addu       $a1, $k0, $zero
/* 15188 80039D88 3C048005 */  lui        $a0, %hi(D_80052BE8)
/* 1518C 80039D8C 0C00E7F7 */  jal        func_80039FDC
/* 15190 80039D90 24842BE8 */   addiu     $a0, $a0, %lo(D_80052BE8)
/* 15194 80039D94 0800E80D */  j          func_8003A034
/* 15198 80039D98 00000000 */   nop
.L80039D9C:
/* 1519C 80039D9C 3C098005 */  lui        $t1, %hi(D_80052BE8)
/* 151A0 80039DA0 25292BE8 */  addiu      $t1, $t1, %lo(D_80052BE8)
/* 151A4 80039DA4 8D2A0000 */  lw         $t2, 0x0($t1)
/* 151A8 80039DA8 AF4A0000 */  sw         $t2, 0x0($k0) # handwritten instruction
/* 151AC 80039DAC 0800E80D */  j          func_8003A034
/* 151B0 80039DB0 AD3A0000 */   sw        $k0, 0x0($t1) # handwritten instruction
.L80039DB4:
/* 151B4 80039DB4 3C018005 */  lui        $at, %hi(D_80052BF4)
/* 151B8 80039DB8 AC3A2BF4 */  sw         $k0, %lo(D_80052BF4)($at) # handwritten instruction
/* 151BC 80039DBC 24090001 */  addiu      $t1, $zero, 0x1
/* 151C0 80039DC0 A7490010 */  sh         $t1, 0x10($k0) # handwritten instruction
/* 151C4 80039DC4 24090002 */  addiu      $t1, $zero, 0x2
/* 151C8 80039DC8 A7490012 */  sh         $t1, 0x12($k0) # handwritten instruction
/* 151CC 80039DCC 400A4000 */  mfc0       $t2, $8 # handwritten instruction
/* 151D0 80039DD0 AF4A0124 */  sw         $t2, 0x124($k0) # handwritten instruction
/* 151D4 80039DD4 0C00E779 */  jal        func_80039DE4
/* 151D8 80039DD8 24040060 */   addiu     $a0, $zero, 0x60
/* 151DC 80039DDC 0800E80D */  j          func_8003A034
/* 151E0 80039DE0 00000000 */   nop
glabel func_80039DE4
/* 151E4 80039DE4 03E09021 */  addu       $s2, $ra, $zero
/* 151E8 80039DE8 3C0A801B */  lui        $t2, %hi(D_801AAB98)
/* 151EC 80039DEC 254AAB98 */  addiu      $t2, $t2, %lo(D_801AAB98)
/* 151F0 80039DF0 01445021 */  addu       $t2, $t2, $a0
/* 151F4 80039DF4 8D490000 */  lw         $t1, 0x0($t2)
/* 151F8 80039DF8 11200027 */  beqz       $t1, .L80039E98
/* 151FC 80039DFC 00000000 */   nop
/* 15200 80039E00 8D2B0008 */  lw         $t3, 0x8($t1)
/* 15204 80039E04 8D2C0010 */  lw         $t4, 0x10($t1)
/* 15208 80039E08 016C082A */  slt        $at, $t3, $t4
/* 1520C 80039E0C 10200022 */  beqz       $at, .L80039E98
/* 15210 80039E10 00000000 */   nop
/* 15214 80039E14 8D2D000C */  lw         $t5, 0xC($t1)
/* 15218 80039E18 01AB6821 */  addu       $t5, $t5, $t3
/* 1521C 80039E1C 01AC001A */  div        $zero, $t5, $t4
/* 15220 80039E20 15800002 */  bnez       $t4, .L80039E2C
/* 15224 80039E24 00000000 */   nop
/* 15228 80039E28 0007000D */  break      7
.L80039E2C:
/* 1522C 80039E2C 2401FFFF */  addiu      $at, $zero, -0x1
/* 15230 80039E30 15810004 */  bne        $t4, $at, .L80039E44
/* 15234 80039E34 3C018000 */   lui       $at, (0x80000000 >> 16)
/* 15238 80039E38 15A10002 */  bne        $t5, $at, .L80039E44
/* 1523C 80039E3C 00000000 */   nop
/* 15240 80039E40 0006000D */  break      6
.L80039E44:
/* 15244 80039E44 00006810 */  mfhi       $t5
/* 15248 80039E48 8D2C0014 */  lw         $t4, 0x14($t1)
/* 1524C 80039E4C 24010004 */  addiu      $at, $zero, 0x4
/* 15250 80039E50 01A10018 */  mult       $t5, $at
/* 15254 80039E54 00006812 */  mflo       $t5
/* 15258 80039E58 018D6021 */  addu       $t4, $t4, $t5
/* 1525C 80039E5C 8D4D0004 */  lw         $t5, 0x4($t2)
/* 15260 80039E60 AD8D0000 */  sw         $t5, 0x0($t4)
/* 15264 80039E64 256A0001 */  addiu      $t2, $t3, 0x1
/* 15268 80039E68 AD2A0008 */  sw         $t2, 0x8($t1)
/* 1526C 80039E6C 8D2A0000 */  lw         $t2, 0x0($t1)
/* 15270 80039E70 8D4B0000 */  lw         $t3, 0x0($t2)
/* 15274 80039E74 11600008 */  beqz       $t3, .L80039E98
/* 15278 80039E78 00000000 */   nop
/* 1527C 80039E7C 0C00E809 */  jal        func_8003A024
/* 15280 80039E80 01202021 */   addu      $a0, $t1, $zero
/* 15284 80039E84 00405021 */  addu       $t2, $v0, $zero
/* 15288 80039E88 01402821 */  addu       $a1, $t2, $zero
/* 1528C 80039E8C 3C048005 */  lui        $a0, %hi(D_80052BE8)
/* 15290 80039E90 0C00E7F7 */  jal        func_80039FDC
/* 15294 80039E94 24842BE8 */   addiu     $a0, $a0, %lo(D_80052BE8)
.L80039E98:
/* 15298 80039E98 02400008 */  jr         $s2
/* 1529C 80039E9C 00000000 */   nop
.L80039EA0:
/* 152A0 80039EA0 3C013000 */  lui        $at, (0x30000000 >> 16)
/* 152A4 80039EA4 01014824 */  and        $t1, $t0, $at
/* 152A8 80039EA8 00094F02 */  srl        $t1, $t1, 28
/* 152AC 80039EAC 240A0001 */  addiu      $t2, $zero, 0x1
/* 152B0 80039EB0 152AFFC0 */  bne        $t1, $t2, .L80039DB4
/* 152B4 80039EB4 00000000 */   nop
/* 152B8 80039EB8 24090001 */  addiu      $t1, $zero, 0x1
/* 152BC 80039EBC AF490018 */  sw         $t1, 0x18($k0) # handwritten instruction
/* 152C0 80039EC0 8F5B0118 */  lw         $k1, 0x118($k0) # handwritten instruction
/* 152C4 80039EC4 3C012000 */  lui        $at, (0x20000000 >> 16)
/* 152C8 80039EC8 0361D825 */  or         $k1, $k1, $at
/* 152CC 80039ECC 1000FFB3 */  b          .L80039D9C
/* 152D0 80039ED0 AF5B0118 */   sw        $k1, 0x118($k0) # handwritten instruction

# Handwritten function
glabel func_80039ED4
/* 152D4 80039ED4 3C058005 */  lui        $a1, %hi(D_80052BF0)
/* 152D8 80039ED8 8CA52BF0 */  lw         $a1, %lo(D_80052BF0)($a1)
/* 152DC 80039EDC 40086000 */  mfc0       $t0, $12 # handwritten instruction
/* 152E0 80039EE0 35080002 */  ori        $t0, $t0, 0x2
/* 152E4 80039EE4 ACA80118 */  sw         $t0, 0x118($a1)
/* 152E8 80039EE8 FCB00098 */  sd         $s0, 0x98($a1)
/* 152EC 80039EEC FCB100A0 */  sd         $s1, 0xA0($a1)
/* 152F0 80039EF0 FCB200A8 */  sd         $s2, 0xA8($a1)
/* 152F4 80039EF4 FCB300B0 */  sd         $s3, 0xB0($a1)
/* 152F8 80039EF8 FCB400B8 */  sd         $s4, 0xB8($a1)
/* 152FC 80039EFC FCB500C0 */  sd         $s5, 0xC0($a1)
/* 15300 80039F00 FCB600C8 */  sd         $s6, 0xC8($a1)
/* 15304 80039F04 FCB700D0 */  sd         $s7, 0xD0($a1)
/* 15308 80039F08 FCBC00E8 */  sd         $gp, 0xE8($a1)
/* 1530C 80039F0C FCBD00F0 */  sd         $sp, 0xF0($a1)
/* 15310 80039F10 FCBE00F8 */  sd         $fp, 0xF8($a1)
/* 15314 80039F14 FCBF0100 */  sd         $ra, 0x100($a1)
/* 15318 80039F18 ACBF011C */  sw         $ra, 0x11C($a1)
/* 1531C 80039F1C 8CBB0018 */  lw         $k1, 0x18($a1) # handwritten instruction
/* 15320 80039F20 1360000A */  beqz       $k1, .L80039F4C # handwritten instruction
/* 15324 80039F24 00000000 */   nop
/* 15328 80039F28 445BF800 */  cfc1       $k1, $31
/* 1532C 80039F2C 00000000 */  nop
/* 15330 80039F30 ACBB012C */  sw         $k1, 0x12C($a1) # handwritten instruction
/* 15334 80039F34 F4B40180 */  sdc1       $f20, 0x180($a1)
/* 15338 80039F38 F4B60188 */  sdc1       $f22, 0x188($a1)
/* 1533C 80039F3C F4B80190 */  sdc1       $f24, 0x190($a1)
/* 15340 80039F40 F4BA0198 */  sdc1       $f26, 0x198($a1)
/* 15344 80039F44 F4BC01A0 */  sdc1       $f28, 0x1A0($a1)
/* 15348 80039F48 F4BE01A8 */  sdc1       $f30, 0x1A8($a1)
.L80039F4C:
/* 1534C 80039F4C 8CBB0118 */  lw         $k1, 0x118($a1) # handwritten instruction
/* 15350 80039F50 3369FF00 */  andi       $t1, $k1, 0xFF00 # handwritten instruction
/* 15354 80039F54 1120000D */  beqz       $t1, .L80039F8C
/* 15358 80039F58 00000000 */   nop
/* 1535C 80039F5C 3C088005 */  lui        $t0, %hi(D_80053DE0)
/* 15360 80039F60 25083DE0 */  addiu      $t0, $t0, %lo(D_80053DE0)
/* 15364 80039F64 8D080000 */  lw         $t0, 0x0($t0)
/* 15368 80039F68 2401FFFF */  addiu      $at, $zero, -0x1
/* 1536C 80039F6C 01014026 */  xor        $t0, $t0, $at
/* 15370 80039F70 3108FF00 */  andi       $t0, $t0, 0xFF00
/* 15374 80039F74 01284825 */  or         $t1, $t1, $t0
/* 15378 80039F78 3C01FFFF */  lui        $at, (0xFFFF00FF >> 16)
/* 1537C 80039F7C 342100FF */  ori        $at, $at, (0xFFFF00FF & 0xFFFF)
/* 15380 80039F80 0361D824 */  and        $k1, $k1, $at
/* 15384 80039F84 0369D825 */  or         $k1, $k1, $t1
/* 15388 80039F88 ACBB0118 */  sw         $k1, 0x118($a1) # handwritten instruction
.L80039F8C:
/* 1538C 80039F8C 3C1BA430 */  lui        $k1, %hi(D_A430000C) # handwritten instruction
/* 15390 80039F90 8F7B000C */  lw         $k1, %lo(D_A430000C)($k1) # handwritten instruction
/* 15394 80039F94 1360000B */  beqz       $k1, .L80039FC4 # handwritten instruction
/* 15398 80039F98 00000000 */   nop
/* 1539C 80039F9C 3C1A8005 */  lui        $k0, %hi(D_80053DE0) # handwritten instruction
/* 153A0 80039FA0 275A3DE0 */  addiu      $k0, $k0, %lo(D_80053DE0) # handwritten instruction
/* 153A4 80039FA4 8F5A0000 */  lw         $k0, 0x0($k0) # handwritten instruction
/* 153A8 80039FA8 001AD402 */  srl        $k0, $k0, 16
/* 153AC 80039FAC 2401FFFF */  addiu      $at, $zero, -0x1
/* 153B0 80039FB0 0341D026 */  xor        $k0, $k0, $at
/* 153B4 80039FB4 335A003F */  andi       $k0, $k0, 0x3F # handwritten instruction
/* 153B8 80039FB8 8CA80128 */  lw         $t0, 0x128($a1)
/* 153BC 80039FBC 0348D024 */  and        $k0, $k0, $t0
/* 153C0 80039FC0 037AD825 */  or         $k1, $k1, $k0
.L80039FC4:
/* 153C4 80039FC4 10800003 */  beqz       $a0, .L80039FD4
/* 153C8 80039FC8 ACBB0128 */   sw        $k1, 0x128($a1) # handwritten instruction
/* 153CC 80039FCC 0C00E7F7 */  jal        func_80039FDC
/* 153D0 80039FD0 00000000 */   nop
.L80039FD4:
/* 153D4 80039FD4 0800E80D */  j          func_8003A034
/* 153D8 80039FD8 00000000 */   nop

glabel func_80039FDC
/* 153DC 80039FDC 0080C821 */  addu       $t9, $a0, $zero
/* 153E0 80039FE0 8C980000 */  lw         $t8, 0x0($a0)
/* 153E4 80039FE4 8CAF0004 */  lw         $t7, 0x4($a1)
/* 153E8 80039FE8 8F0E0004 */  lw         $t6, 0x4($t8)
/* 153EC 80039FEC 01CF082A */  slt        $at, $t6, $t7
/* 153F0 80039FF0 14200007 */  bnez       $at, .L8003A010
/* 153F4 80039FF4 00000000 */   nop
.L80039FF8:
/* 153F8 80039FF8 0300C821 */  addu       $t9, $t8, $zero
/* 153FC 80039FFC 8F180000 */  lw         $t8, 0x0($t8)
/* 15400 8003A000 8F0E0004 */  lw         $t6, 0x4($t8)
/* 15404 8003A004 01CF082A */  slt        $at, $t6, $t7
/* 15408 8003A008 1020FFFB */  beqz       $at, .L80039FF8
/* 1540C 8003A00C 00000000 */   nop
.L8003A010:
/* 15410 8003A010 8F380000 */  lw         $t8, 0x0($t9)
/* 15414 8003A014 ACB80000 */  sw         $t8, 0x0($a1)
/* 15418 8003A018 AF250000 */  sw         $a1, 0x0($t9)
/* 1541C 8003A01C 03E00008 */  jr         $ra
/* 15420 8003A020 ACA40008 */   sw        $a0, 0x8($a1)

glabel func_8003A024
/* 15424 8003A024 8C820000 */  lw         $v0, 0x0($a0)
/* 15428 8003A028 8C590000 */  lw         $t9, 0x0($v0)
/* 1542C 8003A02C 03E00008 */  jr         $ra
/* 15430 8003A030 AC990000 */   sw        $t9, 0x0($a0)

# Handwritten function
glabel func_8003A034
/* 15434 8003A034 3C048005 */  lui        $a0, %hi(D_80052BE8)
/* 15438 8003A038 0C00E809 */  jal        func_8003A024
/* 1543C 8003A03C 24842BE8 */   addiu     $a0, $a0, %lo(D_80052BE8)
/* 15440 8003A040 3C018005 */  lui        $at, %hi(D_80052BF0)
/* 15444 8003A044 AC222BF0 */  sw         $v0, %lo(D_80052BF0)($at)
/* 15448 8003A048 24080004 */  addiu      $t0, $zero, 0x4
/* 1544C 8003A04C A4480010 */  sh         $t0, 0x10($v0)
/* 15450 8003A050 0040D021 */  addu       $k0, $v0, $zero
.L8003A054:
/* 15454 8003A054 8F5B0118 */  lw         $k1, 0x118($k0) # handwritten instruction
/* 15458 8003A058 3C088005 */  lui        $t0, %hi(D_80053DE0)
/* 1545C 8003A05C 25083DE0 */  addiu      $t0, $t0, %lo(D_80053DE0)
/* 15460 8003A060 8D080000 */  lw         $t0, 0x0($t0)
/* 15464 8003A064 3108FF00 */  andi       $t0, $t0, 0xFF00
/* 15468 8003A068 3369FF00 */  andi       $t1, $k1, 0xFF00 # handwritten instruction
/* 1546C 8003A06C 01284824 */  and        $t1, $t1, $t0
/* 15470 8003A070 3C01FFFF */  lui        $at, (0xFFFF00FF >> 16)
/* 15474 8003A074 342100FF */  ori        $at, $at, (0xFFFF00FF & 0xFFFF)
/* 15478 8003A078 0361D824 */  and        $k1, $k1, $at
/* 1547C 8003A07C 0369D825 */  or         $k1, $k1, $t1
/* 15480 8003A080 409B6000 */  mtc0       $k1, $12 # handwritten instruction
/* 15484 8003A084 DF410020 */  ld         $at, 0x20($k0) # handwritten instruction
/* 15488 8003A088 DF420028 */  ld         $v0, 0x28($k0) # handwritten instruction
/* 1548C 8003A08C DF430030 */  ld         $v1, 0x30($k0) # handwritten instruction
/* 15490 8003A090 DF440038 */  ld         $a0, 0x38($k0) # handwritten instruction
/* 15494 8003A094 DF450040 */  ld         $a1, 0x40($k0) # handwritten instruction
/* 15498 8003A098 DF460048 */  ld         $a2, 0x48($k0) # handwritten instruction
/* 1549C 8003A09C DF470050 */  ld         $a3, 0x50($k0) # handwritten instruction
/* 154A0 8003A0A0 DF480058 */  ld         $t0, 0x58($k0) # handwritten instruction
/* 154A4 8003A0A4 DF490060 */  ld         $t1, 0x60($k0) # handwritten instruction
/* 154A8 8003A0A8 DF4A0068 */  ld         $t2, 0x68($k0) # handwritten instruction
/* 154AC 8003A0AC DF4B0070 */  ld         $t3, 0x70($k0) # handwritten instruction
/* 154B0 8003A0B0 DF4C0078 */  ld         $t4, 0x78($k0) # handwritten instruction
/* 154B4 8003A0B4 DF4D0080 */  ld         $t5, 0x80($k0) # handwritten instruction
/* 154B8 8003A0B8 DF4E0088 */  ld         $t6, 0x88($k0) # handwritten instruction
/* 154BC 8003A0BC DF4F0090 */  ld         $t7, 0x90($k0) # handwritten instruction
/* 154C0 8003A0C0 DF500098 */  ld         $s0, 0x98($k0) # handwritten instruction
/* 154C4 8003A0C4 DF5100A0 */  ld         $s1, 0xA0($k0) # handwritten instruction
/* 154C8 8003A0C8 DF5200A8 */  ld         $s2, 0xA8($k0) # handwritten instruction
/* 154CC 8003A0CC DF5300B0 */  ld         $s3, 0xB0($k0) # handwritten instruction
/* 154D0 8003A0D0 DF5400B8 */  ld         $s4, 0xB8($k0) # handwritten instruction
/* 154D4 8003A0D4 DF5500C0 */  ld         $s5, 0xC0($k0) # handwritten instruction
/* 154D8 8003A0D8 DF5600C8 */  ld         $s6, 0xC8($k0) # handwritten instruction
/* 154DC 8003A0DC DF5700D0 */  ld         $s7, 0xD0($k0) # handwritten instruction
/* 154E0 8003A0E0 DF5800D8 */  ld         $t8, 0xD8($k0) # handwritten instruction
/* 154E4 8003A0E4 DF5900E0 */  ld         $t9, 0xE0($k0) # handwritten instruction
/* 154E8 8003A0E8 DF5C00E8 */  ld         $gp, 0xE8($k0) # handwritten instruction
/* 154EC 8003A0EC DF5D00F0 */  ld         $sp, 0xF0($k0) # handwritten instruction
/* 154F0 8003A0F0 DF5E00F8 */  ld         $fp, 0xF8($k0) # handwritten instruction
/* 154F4 8003A0F4 DF5F0100 */  ld         $ra, 0x100($k0) # handwritten instruction
/* 154F8 8003A0F8 DF5B0108 */  ld         $k1, 0x108($k0) # handwritten instruction
/* 154FC 8003A0FC 03600013 */  mtlo       $k1
/* 15500 8003A100 DF5B0110 */  ld         $k1, 0x110($k0) # handwritten instruction
/* 15504 8003A104 03600011 */  mthi       $k1
/* 15508 8003A108 8F5B011C */  lw         $k1, 0x11C($k0) # handwritten instruction
/* 1550C 8003A10C 409B7000 */  mtc0       $k1, $14 # handwritten instruction
/* 15510 8003A110 8F5B0018 */  lw         $k1, 0x18($k0) # handwritten instruction
/* 15514 8003A114 13600013 */  beqz       $k1, .L8003A164 # handwritten instruction
/* 15518 8003A118 00000000 */   nop
/* 1551C 8003A11C 8F5B012C */  lw         $k1, 0x12C($k0) # handwritten instruction
/* 15520 8003A120 44DBF800 */  ctc1       $k1, $31
/* 15524 8003A124 D7400130 */  ldc1       $f0, 0x130($k0)
/* 15528 8003A128 D7420138 */  ldc1       $f2, 0x138($k0)
/* 1552C 8003A12C D7440140 */  ldc1       $f4, 0x140($k0)
/* 15530 8003A130 D7460148 */  ldc1       $f6, 0x148($k0)
/* 15534 8003A134 D7480150 */  ldc1       $f8, 0x150($k0)
/* 15538 8003A138 D74A0158 */  ldc1       $f10, 0x158($k0)
/* 1553C 8003A13C D74C0160 */  ldc1       $f12, 0x160($k0)
/* 15540 8003A140 D74E0168 */  ldc1       $f14, 0x168($k0)
/* 15544 8003A144 D7500170 */  ldc1       $f16, 0x170($k0)
/* 15548 8003A148 D7520178 */  ldc1       $f18, 0x178($k0)
/* 1554C 8003A14C D7540180 */  ldc1       $f20, 0x180($k0)
/* 15550 8003A150 D7560188 */  ldc1       $f22, 0x188($k0)
/* 15554 8003A154 D7580190 */  ldc1       $f24, 0x190($k0)
/* 15558 8003A158 D75A0198 */  ldc1       $f26, 0x198($k0)
/* 1555C 8003A15C D75C01A0 */  ldc1       $f28, 0x1A0($k0)
/* 15560 8003A160 D75E01A8 */  ldc1       $f30, 0x1A8($k0)
.L8003A164:
/* 15564 8003A164 8F5B0128 */  lw         $k1, 0x128($k0) # handwritten instruction
/* 15568 8003A168 3C1A8005 */  lui        $k0, %hi(D_80053DE0) # handwritten instruction
/* 1556C 8003A16C 275A3DE0 */  addiu      $k0, $k0, %lo(D_80053DE0) # handwritten instruction
/* 15570 8003A170 8F5A0000 */  lw         $k0, 0x0($k0) # handwritten instruction
/* 15574 8003A174 001AD402 */  srl        $k0, $k0, 16
/* 15578 8003A178 037AD824 */  and        $k1, $k1, $k0
/* 1557C 8003A17C 001BD840 */  sll        $k1, $k1, 1
/* 15580 8003A180 3C1A8006 */  lui        $k0, %hi(D_80058610) # handwritten instruction
/* 15584 8003A184 275A8610 */  addiu      $k0, $k0, %lo(D_80058610) # handwritten instruction
/* 15588 8003A188 037AD821 */  addu       $k1, $k1, $k0
/* 1558C 8003A18C 977B0000 */  lhu        $k1, 0x0($k1) # handwritten instruction
/* 15590 8003A190 3C1AA430 */  lui        $k0, (0xA430000C >> 16) # handwritten instruction
/* 15594 8003A194 375A000C */  ori        $k0, $k0, (0xA430000C & 0xFFFF) # handwritten instruction
/* 15598 8003A198 AF5B0000 */  sw         $k1, 0x0($k0) # handwritten instruction
/* 1559C 8003A19C 00000000 */  nop
/* 155A0 8003A1A0 00000000 */  nop
/* 155A4 8003A1A4 00000000 */  nop
/* 155A8 8003A1A8 00000000 */  nop
/* 155AC 8003A1AC 42000018 */  eret # handwritten instruction
D_8003A1B0:
/* 155B0 8003A1B0 00002021 */  addu       $a0, $zero, $zero
/* 155B4 8003A1B4 0C00F5DC */  jal        func_8003D770
/* 155B8 8003A1B8 00000000 */   nop
/* 155BC 8003A1BC 00000000 */  nop
