.include "macro.inc"

/* assembler directives */
.set noat
.set noreorder
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.12.1 */

# Handwritten function
glabel func_8003A1C0
/* 155C0 8003A1C0 3C0A8005 */  lui        $t2, %hi(D_80053DE0)
/* 155C4 8003A1C4 254A3DE0 */  addiu      $t2, $t2, %lo(D_80053DE0)
/* 155C8 8003A1C8 8D4B0000 */  lw         $t3, 0x0($t2)
/* 155CC 8003A1CC 316BFF00 */  andi       $t3, $t3, 0xFF00
/* 155D0 8003A1D0 40086000 */  mfc0       $t0, $12 # handwritten instruction
/* 155D4 8003A1D4 2401FFFE */  addiu      $at, $zero, -0x2
/* 155D8 8003A1D8 01014824 */  and        $t1, $t0, $at
/* 155DC 8003A1DC 40896000 */  mtc0       $t1, $12 # handwritten instruction
/* 155E0 8003A1E0 31020001 */  andi       $v0, $t0, 0x1
/* 155E4 8003A1E4 8D480000 */  lw         $t0, 0x0($t2)
/* 155E8 8003A1E8 3108FF00 */  andi       $t0, $t0, 0xFF00
/* 155EC 8003A1EC 110B000E */  beq        $t0, $t3, .L8003A228
/* 155F0 8003A1F0 3C0A8005 */   lui       $t2, %hi(D_80052BF0)
/* 155F4 8003A1F4 254A2BF0 */  addiu      $t2, $t2, %lo(D_80052BF0)
/* 155F8 8003A1F8 8D490118 */  lw         $t1, 0x118($t2)
/* 155FC 8003A1FC 312AFF00 */  andi       $t2, $t1, 0xFF00
/* 15600 8003A200 01485024 */  and        $t2, $t2, $t0
/* 15604 8003A204 3C01FFFF */  lui        $at, (0xFFFF00FF >> 16)
/* 15608 8003A208 342100FF */  ori        $at, $at, (0xFFFF00FF & 0xFFFF)
/* 1560C 8003A20C 01214824 */  and        $t1, $t1, $at
/* 15610 8003A210 012A4825 */  or         $t1, $t1, $t2
/* 15614 8003A214 2401FFFE */  addiu      $at, $zero, -0x2
/* 15618 8003A218 01214824 */  and        $t1, $t1, $at
/* 1561C 8003A21C 40896000 */  mtc0       $t1, $12 # handwritten instruction
/* 15620 8003A220 00000000 */  nop
/* 15624 8003A224 00000000 */  nop
.L8003A228:
/* 15628 8003A228 03E00008 */  jr         $ra
/* 1562C 8003A22C 00000000 */   nop

# Handwritten function
glabel __osRestoreInt
/* 15630 8003A230 40086000 */  mfc0       $t0, $12 # handwritten instruction
/* 15634 8003A234 01044025 */  or         $t0, $t0, $a0
/* 15638 8003A238 40886000 */  mtc0       $t0, $12 # handwritten instruction
/* 1563C 8003A23C 00000000 */  nop
/* 15640 8003A240 00000000 */  nop
/* 15644 8003A244 03E00008 */  jr         $ra
/* 15648 8003A248 00000000 */   nop
/* 1564C 8003A24C 00000000 */  nop
