.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.12.1 */

# Handwritten function
glabel osInvalDCache
/* AA20 8002F620 18A00020 */  blez       $a1, .L8002F6A4
/* AA24 8002F624 00000000 */   nop
/* AA28 8002F628 240B2000 */  addiu      $t3, $zero, 0x2000
/* AA2C 8002F62C 00AB082B */  sltu       $at, $a1, $t3
/* AA30 8002F630 1020001E */  beqz       $at, .L8002F6AC
/* AA34 8002F634 00000000 */   nop
/* AA38 8002F638 00804021 */  addu       $t0, $a0, $zero
/* AA3C 8002F63C 00854821 */  addu       $t1, $a0, $a1
/* AA40 8002F640 0109082B */  sltu       $at, $t0, $t1
/* AA44 8002F644 10200017 */  beqz       $at, .L8002F6A4
/* AA48 8002F648 00000000 */   nop
/* AA4C 8002F64C 2529FFF0 */  addiu      $t1, $t1, -0x10
/* AA50 8002F650 310A000F */  andi       $t2, $t0, 0xF
/* AA54 8002F654 11400007 */  beqz       $t2, .L8002F674
/* AA58 8002F658 00000000 */   nop
/* AA5C 8002F65C 010A4023 */  subu       $t0, $t0, $t2
/* AA60 8002F660 BD150000 */  cache      0x15, 0x0($t0) # handwritten instruction
/* AA64 8002F664 0109082B */  sltu       $at, $t0, $t1
/* AA68 8002F668 1020000E */  beqz       $at, .L8002F6A4
/* AA6C 8002F66C 00000000 */   nop
/* AA70 8002F670 25080010 */  addiu      $t0, $t0, 0x10
.L8002F674:
/* AA74 8002F674 312A000F */  andi       $t2, $t1, 0xF
/* AA78 8002F678 11400006 */  beqz       $t2, .L8002F694
/* AA7C 8002F67C 00000000 */   nop
/* AA80 8002F680 012A4823 */  subu       $t1, $t1, $t2
/* AA84 8002F684 BD350010 */  cache      0x15, 0x10($t1) # handwritten instruction
/* AA88 8002F688 0128082B */  sltu       $at, $t1, $t0
/* AA8C 8002F68C 14200005 */  bnez       $at, .L8002F6A4
/* AA90 8002F690 00000000 */   nop
.L8002F694:
/* AA94 8002F694 BD110000 */  cache      0x11, 0x0($t0) # handwritten instruction
/* AA98 8002F698 0109082B */  sltu       $at, $t0, $t1
/* AA9C 8002F69C 1420FFFD */  bnez       $at, .L8002F694
/* AAA0 8002F6A0 25080010 */   addiu     $t0, $t0, 0x10
.L8002F6A4:
/* AAA4 8002F6A4 03E00008 */  jr         $ra
/* AAA8 8002F6A8 00000000 */   nop
.L8002F6AC:
/* AAAC 8002F6AC 3C088000 */  lui        $t0, 0x8000
/* AAB0 8002F6B0 010B4821 */  addu       $t1, $t0, $t3
/* AAB4 8002F6B4 2529FFF0 */  addiu      $t1, $t1, -0x10
.L8002F6B8:
/* AAB8 8002F6B8 BD010000 */  cache      0x01, 0x0($t0) # handwritten instruction
/* AABC 8002F6BC 0109082B */  sltu       $at, $t0, $t1
/* AAC0 8002F6C0 1420FFFD */  bnez       $at, .L8002F6B8
/* AAC4 8002F6C4 25080010 */   addiu     $t0, $t0, (0x80000010 & 0xFFFF)
/* AAC8 8002F6C8 03E00008 */  jr         $ra
/* AACC 8002F6CC 00000000 */   nop
