.include "macro.inc"

/* assembler directives */
.set noat
.set noreorder
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.12.1 */

# Handwritten function
glabel func_8003D890
/* 18C90 8003D890 40085000 */  mfc0       $t0, $10 # handwritten instruction
/* 18C94 8003D894 2409001F */  addiu      $t1, $zero, 0x1F
/* 18C98 8003D898 40890000 */  mtc0       $t1, $0 # handwritten instruction
/* 18C9C 8003D89C 40802800 */  mtc0       $zero, $5 # handwritten instruction
/* 18CA0 8003D8A0 240A0017 */  addiu      $t2, $zero, 0x17
/* 18CA4 8003D8A4 3C09C000 */  lui        $t1, (0xC0000000 >> 16)
/* 18CA8 8003D8A8 40895000 */  mtc0       $t1, $10 # handwritten instruction
/* 18CAC 8003D8AC 3C098000 */  lui        $t1, (0x80000000 >> 16)
/* 18CB0 8003D8B0 00095982 */  srl        $t3, $t1, 6
/* 18CB4 8003D8B4 016A5825 */  or         $t3, $t3, $t2
/* 18CB8 8003D8B8 408B1000 */  mtc0       $t3, $2 # handwritten instruction
/* 18CBC 8003D8BC 24090001 */  addiu      $t1, $zero, 0x1
/* 18CC0 8003D8C0 40891800 */  mtc0       $t1, $3 # handwritten instruction
/* 18CC4 8003D8C4 00000000 */  nop
/* 18CC8 8003D8C8 42000002 */  tlbwi # handwritten instruction
/* 18CCC 8003D8CC 00000000 */  nop
/* 18CD0 8003D8D0 00000000 */  nop
/* 18CD4 8003D8D4 00000000 */  nop
/* 18CD8 8003D8D8 00000000 */  nop
/* 18CDC 8003D8DC 40885000 */  mtc0       $t0, $10 # handwritten instruction
/* 18CE0 8003D8E0 03E00008 */  jr         $ra
/* 18CE4 8003D8E4 00000000 */   nop
/* 18CE8 8003D8E8 00000000 */  nop
/* 18CEC 8003D8EC 00000000 */  nop
