.include "macro.inc"

/* assembler directives */
.set noat
.set noreorder
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.12.1 */

glabel func_80037EE0
/* 132E0 80037EE0 00000000 */  nop
/* 132E4 80037EE4 00000000 */  nop
/* 132E8 80037EE8 00000000 */  nop
/* 132EC 80037EEC 00000000 */  nop
/* 132F0 80037EF0 00000000 */  nop
/* 132F4 80037EF4 00000000 */  nop
/* 132F8 80037EF8 00000000 */  nop
/* 132FC 80037EFC 00000000 */  nop
/* 13300 80037F00 00000000 */  nop
/* 13304 80037F04 00000000 */  nop
/* 13308 80037F08 00000000 */  nop
/* 1330C 80037F0C 00000000 */  nop
/* 13310 80037F10 00000000 */  nop
/* 13314 80037F14 00000000 */  nop
/* 13318 80037F18 00000000 */  nop
/* 1331C 80037F1C 00000000 */  nop
/* 13320 80037F20 00000000 */  nop
/* 13324 80037F24 00000000 */  nop
/* 13328 80037F28 00000000 */  nop
/* 1332C 80037F2C 00000000 */  nop
/* 13330 80037F30 00000000 */  nop
/* 13334 80037F34 00000000 */  nop
/* 13338 80037F38 00000000 */  nop
/* 1333C 80037F3C 00000000 */  nop
