.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.12.1 */

# Handwritten function
glabel func_80032C90
/* E090 80032C90 40085000 */  mfc0       $t0, $10 # handwritten instruction
/* E094 80032C94 310900FF */  andi       $t1, $t0, 0xFF
/* E098 80032C98 2401E000 */  addiu      $at, $zero, -0x2000
/* E09C 80032C9C 00815024 */  and        $t2, $a0, $at
/* E0A0 80032CA0 012A4825 */  or         $t1, $t1, $t2
/* E0A4 80032CA4 40895000 */  mtc0       $t1, $10 # handwritten instruction
/* E0A8 80032CA8 00000000 */  nop
/* E0AC 80032CAC 00000000 */  nop
/* E0B0 80032CB0 00000000 */  nop
/* E0B4 80032CB4 42000008 */  tlbp # handwritten instruction
/* E0B8 80032CB8 00000000 */  nop
/* E0BC 80032CBC 00000000 */  nop
/* E0C0 80032CC0 400B0000 */  mfc0       $t3, $0 # handwritten instruction
/* E0C4 80032CC4 3C018000 */  lui        $at, (0x80000000 >> 16)
/* E0C8 80032CC8 01615824 */  and        $t3, $t3, $at
/* E0CC 80032CCC 1560001A */  bnez       $t3, .L80032D38
/* E0D0 80032CD0 00000000 */   nop
/* E0D4 80032CD4 42000001 */  tlbr # handwritten instruction
/* E0D8 80032CD8 00000000 */  nop
/* E0DC 80032CDC 00000000 */  nop
/* E0E0 80032CE0 00000000 */  nop
/* E0E4 80032CE4 400B2800 */  mfc0       $t3, $5 # handwritten instruction
/* E0E8 80032CE8 216B2000 */  addi       $t3, $t3, 0x2000 # handwritten instruction
/* E0EC 80032CEC 000B5842 */  srl        $t3, $t3, 1
/* E0F0 80032CF0 01646024 */  and        $t4, $t3, $a0
/* E0F4 80032CF4 15800004 */  bnez       $t4, .L80032D08
/* E0F8 80032CF8 216BFFFF */   addi      $t3, $t3, -0x1 # handwritten instruction
/* E0FC 80032CFC 40021000 */  mfc0       $v0, $2 # handwritten instruction
/* E100 80032D00 10000002 */  b          .L80032D0C
/* E104 80032D04 00000000 */   nop
.L80032D08:
/* E108 80032D08 40021800 */  mfc0       $v0, $3 # handwritten instruction
.L80032D0C:
/* E10C 80032D0C 304D0002 */  andi       $t5, $v0, 0x2
/* E110 80032D10 11A00009 */  beqz       $t5, .L80032D38
/* E114 80032D14 00000000 */   nop
/* E118 80032D18 3C013FFF */  lui        $at, (0x3FFFFFC0 >> 16)
/* E11C 80032D1C 3421FFC0 */  ori        $at, $at, (0x3FFFFFC0 & 0xFFFF)
/* E120 80032D20 00411024 */  and        $v0, $v0, $at
/* E124 80032D24 00021180 */  sll        $v0, $v0, 6
/* E128 80032D28 008B6824 */  and        $t5, $a0, $t3
/* E12C 80032D2C 004D1020 */  add        $v0, $v0, $t5 # handwritten instruction
/* E130 80032D30 10000002 */  b          .L80032D3C
/* E134 80032D34 00000000 */   nop
.L80032D38:
/* E138 80032D38 2402FFFF */  addiu      $v0, $zero, -0x1
.L80032D3C:
/* E13C 80032D3C 40885000 */  mtc0       $t0, $10 # handwritten instruction
/* E140 80032D40 03E00008 */  jr         $ra
/* E144 80032D44 00000000 */   nop
/* E148 80032D48 00000000 */  nop
/* E14C 80032D4C 00000000 */  nop
