.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.12.1 */

glabel func_80042E10
/* 1E210 80042E10 00001021 */  addu       $v0, $zero, $zero
/* 1E214 80042E14 3C08A404 */  lui        $t0, %hi(D_A4040010)
/* 1E218 80042E18 8D080010 */  lw         $t0, %lo(D_A4040010)($t0)
/* 1E21C 80042E1C 31080003 */  andi       $t0, $t0, 0x3
/* 1E220 80042E20 15000002 */  bnez       $t0, .L80042E2C
/* 1E224 80042E24 00000000 */   nop
/* 1E228 80042E28 34420001 */  ori        $v0, $v0, 0x1
.L80042E2C:
/* 1E22C 80042E2C 03E00008 */  jr         $ra
/* 1E230 80042E30 00000000 */   nop

glabel func_80042E34
/* 1E234 80042E34 3C04A404 */  lui        $a0, (0xA4040018 >> 16)
/* 1E238 80042E38 34840018 */  ori        $a0, $a0, (0xA4040018 & 0xFFFF)
.L80042E3C:
/* 1E23C 80042E3C 8C820000 */  lw         $v0, 0x0($a0)
/* 1E240 80042E40 1440FFFE */  bnez       $v0, .L80042E3C
/* 1E244 80042E44 00000000 */   nop
/* 1E248 80042E48 24050082 */  addiu      $a1, $zero, 0x82
/* 1E24C 80042E4C 3C04A404 */  lui        $a0, (0xA4040010 >> 16)
/* 1E250 80042E50 34840010 */  ori        $a0, $a0, (0xA4040010 & 0xFFFF)
/* 1E254 80042E54 AC850000 */  sw         $a1, 0x0($a0)
.L80042E58:
/* 1E258 80042E58 3C04A404 */  lui        $a0, (0xA4040010 >> 16)
/* 1E25C 80042E5C 34840010 */  ori        $a0, $a0, (0xA4040010 & 0xFFFF)
/* 1E260 80042E60 8C820000 */  lw         $v0, 0x0($a0)
/* 1E264 80042E64 30420003 */  andi       $v0, $v0, 0x3
/* 1E268 80042E68 1040FFFB */  beqz       $v0, .L80042E58
/* 1E26C 80042E6C 00000000 */   nop
/* 1E270 80042E70 03E00008 */  jr         $ra
/* 1E274 80042E74 00000000 */   nop

glabel func_80042E78
/* 1E278 80042E78 3C04A404 */  lui        $a0, (0xA4040010 >> 16)
/* 1E27C 80042E7C 34840010 */  ori        $a0, $a0, (0xA4040010 & 0xFFFF)
/* 1E280 80042E80 240500C5 */  addiu      $a1, $zero, 0xC5
/* 1E284 80042E84 1000FFF4 */  b          .L80042E58
/* 1E288 80042E88 AC850000 */   sw        $a1, 0x0($a0)

glabel func_80042E8C
/* 1E28C 80042E8C 3C04A430 */  lui        $a0, (0xA430000C >> 16)
/* 1E290 80042E90 3484000C */  ori        $a0, $a0, (0xA430000C & 0xFFFF)
/* 1E294 80042E94 24050002 */  addiu      $a1, $zero, 0x2
/* 1E298 80042E98 AC850000 */  sw         $a1, 0x0($a0)
/* 1E29C 80042E9C 3C04A404 */  lui        $a0, (0xA4040010 >> 16)
/* 1E2A0 80042EA0 34840010 */  ori        $a0, $a0, (0xA4040010 & 0xFFFF)
/* 1E2A4 80042EA4 24050125 */  addiu      $a1, $zero, 0x125
/* 1E2A8 80042EA8 03E00008 */  jr         $ra
/* 1E2AC 80042EAC AC850000 */   sw        $a1, 0x0($a0)
