.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.12.1 */

# Handwritten function
glabel func_8003CED0
/* 182D0 8003CED0 40845800 */  mtc0       $a0, $11 # handwritten instruction
/* 182D4 8003CED4 03E00008 */  jr         $ra
/* 182D8 8003CED8 00000000 */   nop
/* 182DC 8003CEDC 00000000 */  nop
