.include "macro.inc"

/* assembler directives */
.set noat
.set noreorder
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.12.1 */

glabel func_8003CEE0
/* 182E0 8003CEE0 4442F800 */  cfc1       $v0, $31
/* 182E4 8003CEE4 44C4F800 */  ctc1       $a0, $31
/* 182E8 8003CEE8 03E00008 */  jr         $ra
/* 182EC 8003CEEC 00000000 */   nop
