.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.12.1 */

# Handwritten function
glabel osSetIntMask
/* 9420 8002E020 400C6000 */  mfc0       $t4, $12 # handwritten instruction
/* 9424 8002E024 3182FF01 */  andi       $v0, $t4, 0xFF01
/* 9428 8002E028 3C088005 */  lui        $t0, %hi(D_80053DE0)
/* 942C 8002E02C 25083DE0 */  addiu      $t0, $t0, %lo(D_80053DE0)
/* 9430 8002E030 8D0B0000 */  lw         $t3, 0x0($t0)
/* 9434 8002E034 2401FFFF */  addiu      $at, $zero, -0x1
/* 9438 8002E038 01614026 */  xor        $t0, $t3, $at
/* 943C 8002E03C 3108FF00 */  andi       $t0, $t0, 0xFF00
/* 9440 8002E040 00481025 */  or         $v0, $v0, $t0
/* 9444 8002E044 3C0AA430 */  lui        $t2, %hi(D_A430000C)
/* 9448 8002E048 8D4A000C */  lw         $t2, %lo(D_A430000C)($t2)
/* 944C 8002E04C 11400005 */  beqz       $t2, .L8002E064
/* 9450 8002E050 000B4C02 */   srl       $t1, $t3, 16
/* 9454 8002E054 2401FFFF */  addiu      $at, $zero, -0x1
/* 9458 8002E058 01214826 */  xor        $t1, $t1, $at
/* 945C 8002E05C 3129003F */  andi       $t1, $t1, 0x3F
/* 9460 8002E060 01495025 */  or         $t2, $t2, $t1
.L8002E064:
/* 9464 8002E064 000A5400 */  sll        $t2, $t2, 16
/* 9468 8002E068 004A1025 */  or         $v0, $v0, $t2
/* 946C 8002E06C 3C01003F */  lui        $at, (0x3F0000 >> 16)
/* 9470 8002E070 00814024 */  and        $t0, $a0, $at
/* 9474 8002E074 010B4024 */  and        $t0, $t0, $t3
/* 9478 8002E078 000843C2 */  srl        $t0, $t0, 15
/* 947C 8002E07C 3C0A8006 */  lui        $t2, %hi(D_80058610)
/* 9480 8002E080 01485021 */  addu       $t2, $t2, $t0
/* 9484 8002E084 954A8610 */  lhu        $t2, %lo(D_80058610)($t2)
/* 9488 8002E088 3C01A430 */  lui        $at, %hi(D_A430000C)
/* 948C 8002E08C AC2A000C */  sw         $t2, %lo(D_A430000C)($at)
/* 9490 8002E090 3088FF01 */  andi       $t0, $a0, 0xFF01
/* 9494 8002E094 3169FF00 */  andi       $t1, $t3, 0xFF00
/* 9498 8002E098 01094024 */  and        $t0, $t0, $t1
/* 949C 8002E09C 3C01FFFF */  lui        $at, (0xFFFF00FF >> 16)
/* 94A0 8002E0A0 342100FF */  ori        $at, $at, (0xFFFF00FF & 0xFFFF)
/* 94A4 8002E0A4 01816024 */  and        $t4, $t4, $at
/* 94A8 8002E0A8 01886025 */  or         $t4, $t4, $t0
/* 94AC 8002E0AC 408C6000 */  mtc0       $t4, $12 # handwritten instruction
/* 94B0 8002E0B0 00000000 */  nop
/* 94B4 8002E0B4 00000000 */  nop
/* 94B8 8002E0B8 03E00008 */  jr         $ra
/* 94BC 8002E0BC 00000000 */   nop
