.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.12.1 */

# Handwritten function
glabel func_8003CEF0
/* 182F0 8003CEF0 40846000 */  mtc0       $a0, $12 # handwritten instruction
/* 182F4 8003CEF4 00000000 */  nop
/* 182F8 8003CEF8 03E00008 */  jr         $ra
/* 182FC 8003CEFC 00000000 */   nop
