.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.12.1 */

# Handwritten function
glabel func_8003D8F0
/* 18CF0 8003D8F0 40085000 */  mfc0       $t0, $10 # handwritten instruction
/* 18CF4 8003D8F4 2409001E */  addiu      $t1, $zero, 0x1E
/* 18CF8 8003D8F8 3C0A8000 */  lui        $t2, (0x80000000 >> 16)
/* 18CFC 8003D8FC 408A5000 */  mtc0       $t2, $10 # handwritten instruction
/* 18D00 8003D900 40801000 */  mtc0       $zero, $2 # handwritten instruction
/* 18D04 8003D904 40801800 */  mtc0       $zero, $3 # handwritten instruction
.L8003D908:
/* 18D08 8003D908 40890000 */  mtc0       $t1, $0 # handwritten instruction
/* 18D0C 8003D90C 00000000 */  nop
/* 18D10 8003D910 42000002 */  tlbwi # handwritten instruction
/* 18D14 8003D914 00000000 */  nop
/* 18D18 8003D918 00000000 */  nop
/* 18D1C 8003D91C 2129FFFF */  addi       $t1, $t1, -0x1 # handwritten instruction
/* 18D20 8003D920 0521FFF9 */  bgez       $t1, .L8003D908
/* 18D24 8003D924 00000000 */   nop
/* 18D28 8003D928 40885000 */  mtc0       $t0, $10 # handwritten instruction
/* 18D2C 8003D92C 03E00008 */  jr         $ra
/* 18D30 8003D930 00000000 */   nop
/* 18D34 8003D934 00000000 */  nop
/* 18D38 8003D938 00000000 */  nop
/* 18D3C 8003D93C 00000000 */  nop
