.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.12.1 */

# Handwritten function
glabel osWritebackDCache
/* 15F60 8003AB60 18A00011 */  blez       $a1, .L8003ABA8
/* 15F64 8003AB64 00000000 */   nop
/* 15F68 8003AB68 240B2000 */  addiu      $t3, $zero, 0x2000
/* 15F6C 8003AB6C 00AB082B */  sltu       $at, $a1, $t3
/* 15F70 8003AB70 1020000F */  beqz       $at, .L8003ABB0
/* 15F74 8003AB74 00000000 */   nop
/* 15F78 8003AB78 00804021 */  addu       $t0, $a0, $zero
/* 15F7C 8003AB7C 00854821 */  addu       $t1, $a0, $a1
/* 15F80 8003AB80 0109082B */  sltu       $at, $t0, $t1
/* 15F84 8003AB84 10200008 */  beqz       $at, .L8003ABA8
/* 15F88 8003AB88 00000000 */   nop
/* 15F8C 8003AB8C 2529FFF0 */  addiu      $t1, $t1, -0x10
/* 15F90 8003AB90 310A000F */  andi       $t2, $t0, 0xF
/* 15F94 8003AB94 010A4023 */  subu       $t0, $t0, $t2
.L8003AB98:
/* 15F98 8003AB98 BD190000 */  cache      0x19, 0x0($t0) # handwritten instruction
/* 15F9C 8003AB9C 0109082B */  sltu       $at, $t0, $t1
/* 15FA0 8003ABA0 1420FFFD */  bnez       $at, .L8003AB98
/* 15FA4 8003ABA4 25080010 */   addiu     $t0, $t0, 0x10
.L8003ABA8:
/* 15FA8 8003ABA8 03E00008 */  jr         $ra
/* 15FAC 8003ABAC 00000000 */   nop
.L8003ABB0:
/* 15FB0 8003ABB0 3C088000 */  lui        $t0, 0x8000
/* 15FB4 8003ABB4 010B4821 */  addu       $t1, $t0, $t3
/* 15FB8 8003ABB8 2529FFF0 */  addiu      $t1, $t1, -0x10
.L8003ABBC:
/* 15FBC 8003ABBC BD010000 */  cache      0x01, 0x0($t0) # handwritten instruction
/* 15FC0 8003ABC0 0109082B */  sltu       $at, $t0, $t1
/* 15FC4 8003ABC4 1420FFFD */  bnez       $at, .L8003ABBC
/* 15FC8 8003ABC8 25080010 */   addiu     $t0, $t0, (0x80000010 & 0xFFFF)
/* 15FCC 8003ABCC 03E00008 */  jr         $ra
/* 15FD0 8003ABD0 00000000 */   nop
/* 15FD4 8003ABD4 00000000 */  nop
/* 15FD8 8003ABD8 00000000 */  nop
/* 15FDC 8003ABDC 00000000 */  nop
