.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.12.1 */

glabel func_800467F0
/* 21BF0 800467F0 27BDFFE0 */  addiu      $sp, $sp, -0x20
/* 21BF4 800467F4 AFBF001C */  sw         $ra, 0x1C($sp)
/* 21BF8 800467F8 AFB00018 */  sw         $s0, 0x18($sp)
/* 21BFC 800467FC 0C011A61 */  jal        _pt_puts
/* 21C00 80046800 00808021 */   addu      $s0, $a0, $zero
/* 21C04 80046804 00002021 */  addu       $a0, $zero, $zero
/* 21C08 80046808 92020000 */  lbu        $v0, 0x0($s0)
/* 21C0C 8004680C 10400008 */  beqz       $v0, .L80046830
/* 21C10 80046810 00401821 */   addu      $v1, $v0, $zero
/* 21C14 80046814 00031600 */  sll        $v0, $v1, 24
.L80046818:
/* 21C18 80046818 00022603 */  sra        $a0, $v0, 24
/* 21C1C 8004681C 26100001 */  addiu      $s0, $s0, 0x1
/* 21C20 80046820 92030000 */  lbu        $v1, 0x0($s0)
/* 21C24 80046824 82020000 */  lb         $v0, 0x0($s0)
/* 21C28 80046828 1440FFFB */  bnez       $v0, .L80046818
/* 21C2C 8004682C 00031600 */   sll       $v0, $v1, 24
.L80046830:
/* 21C30 80046830 00801021 */  addu       $v0, $a0, $zero
/* 21C34 80046834 8FBF001C */  lw         $ra, 0x1C($sp)
/* 21C38 80046838 8FB00018 */  lw         $s0, 0x18($sp)
/* 21C3C 8004683C 03E00008 */  jr         $ra
/* 21C40 80046840 27BD0020 */   addiu     $sp, $sp, 0x20
/* 21C44 80046844 00000000 */  nop
/* 21C48 80046848 00000000 */  nop
/* 21C4C 8004684C 00000000 */  nop
