.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.12.1 */

glabel func_80046850
/* 21C50 80046850 F4CC0000 */  sdc1       $f12, 0x0($a2)
/* 21C54 80046854 8CC20000 */  lw         $v0, 0x0($a2)
/* 21C58 80046858 00021D02 */  srl        $v1, $v0, 20
/* 21C5C 8004685C 306307FF */  andi       $v1, $v1, 0x7FF
/* 21C60 80046860 2463FC01 */  addiu      $v1, $v1, -0x3FF
/* 21C64 80046864 04610005 */  bgez       $v1, .L8004687C
/* 21C68 80046868 28620034 */   slti      $v0, $v1, 0x34
/* 21C6C 8004686C ACC00000 */  sw         $zero, 0x0($a2)
/* 21C70 80046870 ACC00004 */  sw         $zero, 0x4($a2)
/* 21C74 80046874 08011A3B */  j          .L800468EC
/* 21C78 80046878 46206006 */   mov.d     $f0, $f12
.L8004687C:
/* 21C7C 8004687C 14400006 */  bnez       $v0, .L80046898
/* 21C80 80046880 2463000C */   addiu     $v1, $v1, 0xC
/* 21C84 80046884 F4CC0000 */  sdc1       $f12, 0x0($a2)
/* 21C88 80046888 44800000 */  mtc1       $zero, $f0
/* 21C8C 8004688C 44800800 */  mtc1       $zero, $f1
/* 21C90 80046890 08011A3B */  j          .L800468EC
/* 21C94 80046894 00000000 */   nop
.L80046898:
/* 21C98 80046898 000328C3 */  sra        $a1, $v1, 3
/* 21C9C 8004689C 00C52021 */  addu       $a0, $a2, $a1
/* 21CA0 800468A0 30630007 */  andi       $v1, $v1, 0x7
/* 21CA4 800468A4 24020008 */  addiu      $v0, $zero, 0x8
/* 21CA8 800468A8 00431023 */  subu       $v0, $v0, $v1
/* 21CAC 800468AC 240300FF */  addiu      $v1, $zero, 0xFF
/* 21CB0 800468B0 00431804 */  sllv       $v1, $v1, $v0
/* 21CB4 800468B4 90820000 */  lbu        $v0, 0x0($a0)
/* 21CB8 800468B8 00431024 */  and        $v0, $v0, $v1
/* 21CBC 800468BC A0820000 */  sb         $v0, 0x0($a0)
/* 21CC0 800468C0 28A20007 */  slti       $v0, $a1, 0x7
/* 21CC4 800468C4 10400007 */  beqz       $v0, .L800468E4
/* 21CC8 800468C8 00000000 */   nop
/* 21CCC 800468CC 24A50001 */  addiu      $a1, $a1, 0x1
.L800468D0:
/* 21CD0 800468D0 00C51021 */  addu       $v0, $a2, $a1
/* 21CD4 800468D4 A0400000 */  sb         $zero, 0x0($v0)
/* 21CD8 800468D8 28A20007 */  slti       $v0, $a1, 0x7
/* 21CDC 800468DC 5440FFFC */  bnel       $v0, $zero, .L800468D0
/* 21CE0 800468E0 24A50001 */   addiu     $a1, $a1, 0x1
.L800468E4:
/* 21CE4 800468E4 D4C00000 */  ldc1       $f0, 0x0($a2)
/* 21CE8 800468E8 46206001 */  sub.d      $f0, $f12, $f0
.L800468EC:
/* 21CEC 800468EC 03E00008 */  jr         $ra
/* 21CF0 800468F0 00000000 */   nop
/* 21CF4 800468F4 00000000 */  nop
/* 21CF8 800468F8 00000000 */  nop
/* 21CFC 800468FC 00000000 */  nop
