.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.12.1 */

glabel putch
/* 21D00 80046900 27BDFFE8 */  addiu      $sp, $sp, -0x18
/* 21D04 80046904 AFBF0014 */  sw         $ra, 0x14($sp)
/* 21D08 80046908 AFB00010 */  sw         $s0, 0x10($sp)
/* 21D0C 8004690C 0C011A51 */  jal        _pt_dsp
/* 21D10 80046910 00808021 */   addu      $s0, $a0, $zero
/* 21D14 80046914 02001021 */  addu       $v0, $s0, $zero
/* 21D18 80046918 8FBF0014 */  lw         $ra, 0x14($sp)
/* 21D1C 8004691C 8FB00010 */  lw         $s0, 0x10($sp)
/* 21D20 80046920 03E00008 */  jr         $ra
/* 21D24 80046924 27BD0018 */   addiu     $sp, $sp, 0x18
/* 21D28 80046928 00000000 */  nop
/* 21D2C 8004692C 00000000 */  nop
