.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.12.1 */

glabel putchar
/* 21710 80046310 27BDFFE8 */  addiu      $sp, $sp, -0x18
/* 21714 80046314 AFBF0014 */  sw         $ra, 0x14($sp)
/* 21718 80046318 AFB00010 */  sw         $s0, 0x10($sp)
/* 2171C 8004631C 00808021 */  addu       $s0, $a0, $zero
/* 21720 80046320 2402000A */  addiu      $v0, $zero, 0xA
/* 21724 80046324 16020003 */  bne        $s0, $v0, .L80046334
/* 21728 80046328 00000000 */   nop
/* 2172C 8004632C 0C011A40 */  jal        putch
/* 21730 80046330 2404000D */   addiu     $a0, $zero, 0xD
.L80046334:
/* 21734 80046334 0C011A40 */  jal        putch
/* 21738 80046338 02002021 */   addu      $a0, $s0, $zero
/* 2173C 8004633C 02001021 */  addu       $v0, $s0, $zero
/* 21740 80046340 8FBF0014 */  lw         $ra, 0x14($sp)
/* 21744 80046344 8FB00010 */  lw         $s0, 0x10($sp)
/* 21748 80046348 03E00008 */  jr         $ra
/* 2174C 8004634C 27BD0018 */   addiu     $sp, $sp, 0x18
