.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.12.1 */

glabel __syscall
/* 21D30 80046930 00800821 */  addu       $at, $a0, $zero
/* 21D34 80046934 00A01021 */  addu       $v0, $a1, $zero
/* 21D38 80046938 00000000 */  nop
/* 21D3C 8004693C 03E00008 */  jr         $ra
/* 21D40 80046940 00201021 */   addu      $v0, $at, $zero

glabel _pt_dsp
/* 21D44 80046944 27BDFFE8 */  addiu      $sp, $sp, -0x18
/* 21D48 80046948 AFBF0010 */  sw         $ra, 0x10($sp)
/* 21D4C 8004694C 00042E00 */  sll        $a1, $a0, 24
/* 21D50 80046950 3404FE00 */  ori        $a0, $zero, 0xFE00
/* 21D54 80046954 0C011A4C */  jal        __syscall
/* 21D58 80046958 00052E03 */   sra       $a1, $a1, 24
/* 21D5C 8004695C 8FBF0010 */  lw         $ra, 0x10($sp)
/* 21D60 80046960 03E00008 */  jr         $ra
/* 21D64 80046964 27BD0018 */   addiu     $sp, $sp, 0x18

glabel _pt_key
/* 21D68 80046968 27BDFFE8 */  addiu      $sp, $sp, -0x18
/* 21D6C 8004696C AFBF0010 */  sw         $ra, 0x10($sp)
/* 21D70 80046970 0C011A4C */  jal        __syscall
/* 21D74 80046974 3404FE01 */   ori       $a0, $zero, 0xFE01
/* 21D78 80046978 8FBF0010 */  lw         $ra, 0x10($sp)
/* 21D7C 8004697C 03E00008 */  jr         $ra
/* 21D80 80046980 27BD0018 */   addiu     $sp, $sp, 0x18

glabel _pt_puts
/* 21D84 80046984 27BDFFE8 */  addiu      $sp, $sp, -0x18
/* 21D88 80046988 AFBF0010 */  sw         $ra, 0x10($sp)
/* 21D8C 8004698C 00802821 */  addu       $a1, $a0, $zero
/* 21D90 80046990 0C011A4C */  jal        __syscall
/* 21D94 80046994 3404FE02 */   ori       $a0, $zero, 0xFE02
/* 21D98 80046998 8FBF0010 */  lw         $ra, 0x10($sp)
/* 21D9C 8004699C 03E00008 */  jr         $ra
/* 21DA0 800469A0 27BD0018 */   addiu     $sp, $sp, 0x18
/* 21DA4 800469A4 00000000 */  nop
/* 21DA8 800469A8 00000000 */  nop
/* 21DAC 800469AC 00000000 */  nop
